### ISSUE TITLE
Shortend URL Public Statistics Page

### ISSUE THREAD

**Issue by aigdonia** [origranot/reduced.to#101]
In Order to make a value for this App not to be another URL shortener, I believe we need to add some numbers.

As A short URL creator I need to track some statistics for the link I just created, I suggest the following number:

- Number of Times this link was opened.
- Geolocation, or list of Referrals where as this link was opened from.

## Acceptance Criteria
- Create a link details page at URL `<domain>/<shortened_link>/stats`.
- this page should display the number of times this link was opened.
- this page should display a brief of maximum 5 referral links that led to this link.
- this page should be publicly accessible.

**Comment by aigdonia** [comment]
@origranot I can happily work on this, also I have another list of features we can include this this nice project

**Comment by origranot** [comment]
Go for it!

**Comment by origranot** [comment]
@aigdonia Any update?

**Comment by aigdonia** [comment]
My work in progress, I had to add storage for counting the visits, this took more than expected, I'll push my work today

**Comment by origranot** [comment]
@aigdonia Great!

**Comment by JoaoVictor6** [comment]
> My work in progress, I had to add storage for counting the visits, and this took more than expected, I'll push my work today

Hello, I'm very interested in this feature, I cloned this repo and I'm developing a little of this. How would you do this count? I imagined creating a key with the following pattern: `${key}+count`

**Comment by origranot** [comment]
> > My work in progress, I had to add storage for counting the visits, and this took more than expected, I'll push my work today
> 
> How would you do this count? I imagined creating a key with the following pattern: `${key}+count`

Hey @JoaoVictor6, we are working to add another database to store authentication and details about every url.
I don't believe it's the best practice to implement this kind of feature on Redis database.

We are still working on it, I hope we will finish soon 😮‍💨

**Comment by Senior-ai** [comment]
@origranot I want to take this challenge. But first, was there any research done regarding storing additional details on each URL using Redis? Is there anything else used infrastructure-wise?

**Comment by origranot** [comment]
> @origranot I want to take this challenge. But first, was there any research done regarding storing additional details on each URL using Redis? Is there anything else used infrastructure-wise?

In-order to understand the current data we store on each link and visits you can check out the Prisma schema.
I will be more than pleased to help you out on Discord.

**Comment by Senior-ai** [comment]
> > @origranot I want to take this challenge. But first, was there any research done regarding storing additional details on each URL using Redis? Is there anything else used infrastructure-wise?
> 
> In-order to understand the current data we store on each link and visits you can check out the Prisma schema. I will be more than happy to assist you out on Discord.

No problem, wrote you everything I need to know (I think) on discord

**Comment by UrielOfir** [comment]
@Senior-ai 
Are you still working on this issue?

**Comment by Senior-ai** [comment]
@UrielOfir yeah I made a pr, I just need extra time for making sure all of the backend works properly for this feature
