### ISSUE TITLE
Custom shortened links

### ISSUE THREAD

**Issue by aigdonia** [origranot/reduced.to#104]
As A Shortened URL creator I need to create custom shortened links.

This is useful for premium users and advanced users.

## Acceptance Criteria
- User should be able to click create custom link button
- user should enter custom link.
- custom link should be validated not to be duplicate, and fulfills length and character validation

**Comment by detronetdip** [comment]
Hey I want to work on this issue @origranot can you please assign me?

**Comment by origranot** [comment]
@aigdonia Amazing idea!

@detronetdip Go for it!
