### ISSUE TITLE
tests: Add tests to shortener controller

### ISSUE THREAD

**Issue by origranot** [origranot/reduced.to#120]
Hey guys, we need to add some tests to our project.
This should cover the tests on the shortener.controller.ts

**Comment by professorjrod** [comment]
can u assign me. what testing library?

**Comment by origranot** [comment]
@professorjrod Thanks!

Our backend framework is nest, tests are with jest.

**Comment by origranot** [comment]
Done https://github.com/origranot/reduced.to/pull/273
