### ISSUE TITLE
Document contribution

### ISSUE THREAD

**Issue by namit343** [origranot/reduced.to#168]
Can I contribute by making document changes and getting them "Hacktoberfest-accepted"?

**Comment by origranot** [comment]
What kind of changes?

**Comment by namit343** [comment]
Basic grammatical changes, or I can help writing any Document files also if you want.

**Comment by origranot** [comment]
You are more than welcome to fix issues with the documentation.
Go for it.

**Comment by cweave** [comment]
I have some questions into which app is the actual app to use, I posted the issue here: https://github.com/origranot/url-shortener/issues/188#issuecomment-1276835683

both wildly different experiences.

**Comment by GuillemPM** [comment]
I will close this issue as it is a generic question. You are free to contribute whenever you want! Thanks!! 🔥
