### ISSUE TITLE
CI Workflow changing EOL

### ISSUE THREAD

**Issue by GuillemPM** [origranot/reduced.to#193]
### Description

Since the postinstall scripts are rebuilding the solution, it generates files with EOLs that doesn't match with the Prettier code style.
Reference to the issue #191 

Whoever, this problem should be mitigated, maybe we need to add Husky? 🤔

### Screenshots

![image](https://user-images.githubusercontent.com/26607131/195470471-00be2928-bd4d-482a-8686-3f278b960e58.png)

**Comment by varunKT001** [comment]
@GuillemPM 
We can add a pre-commit hook that runs prettier before making a commit. 
If this issue is up for grabs, I would like to work on it.

**Comment by GuillemPM** [comment]
How are you planning to do it? 
Would you implement husky?

**Comment by varunKT001** [comment]
@GuillemPM Yes, I will use husky to create a pre-commit hook that will run prettier checks.

**Comment by GuillemPM** [comment]
Could you create a new issue for that? I will close this one
