### ISSUE TITLE
[DOCS] Update gif

### ISSUE THREAD

**Issue by GuillemPM** [origranot/reduced.to#204]
### Description

We need an updated GIF on our README.md!!!

It's important to keep the same size (or very similar) as the current GIF

**Comment by LoicB** [comment]
Hello,
I am trying to update the gif image. But should I use the UI from the latest version? It would give a URL with localhost, which is probably not the best. Alternatively I could use reduced.to but the UI is very similar.

**Comment by GuillemPM** [comment]
Hi, let's wait until we deploy to prod. I'll ping you here

**Comment by GuillemPM** [comment]
@LoicB, app deployed, so go on. Thanks! 🔥

**Comment by amittri1025** [comment]
Hello I solved this issue, update GIFs on homepage , with new website.

**Comment by HridoyHazard** [comment]
#257
here is the pr which have the similar ratio of previous gif

**Comment by origranot** [comment]
Done https://github.com/origranot/reduced.to/pull/257
