### ISSUE TITLE
Changes on the Input Bar

### ISSUE THREAD

**Issue by SugamKuber** [origranot/reduced.to#211]
### Description

I would love to contribute by making changes on the  input bar which has few minor bugs
Please give me the issue

### Screenshots

![image](https://user-images.githubusercontent.com/86460476/195978362-acc6a9ed-538e-4b35-ba0a-bbda96155d1f.png)

**Comment by GuillemPM** [comment]
I have a talk about that just yesterday with @origranot .

Could you explain what are you going to do?
The main task is getting rid of the outboxed line

**Comment by SugamKuber** [comment]
I will just make sure it won't overflow like, I'll make the UI/UX clean
The border kinda looks ugly as of now

**Comment by GuillemPM** [comment]
Make sure to follow the DaisyUI themes guidelines please! Thanks😊

**Comment by SugamKuber** [comment]
Thanks, I'll edit the code soon and make the PR by tomorrow

**Comment by SugamKuber** [comment]
I'm closing this issue
Its daisy UI feature, I dont think I can disable the input box border

**Comment by GuillemPM** [comment]
Just override the class that generates that border
