### ISSUE TITLE
Fix the input bar border when focus

### ISSUE THREAD

**Issue by origranot** [origranot/reduced.to#218]
### Description

Hey Guys 👋 

When the input bar is in focus there is a border that we want to remove.
Looks like we need to override the default Tailwind focus effect:
```css
.input:focus
```

### Screenshots

![image](https://user-images.githubusercontent.com/48911144/196004163-e70fa2b3-45f8-4d35-a257-434759b86f2b.png)

**Comment by mau211** [comment]
@origranot I can take this up

**Comment by origranot** [comment]
> @origranot I can take this up

Go for it, I assigned you.

**Comment by mau211** [comment]
Hey I just opened this pr, do you mind adding the hacktoberfest and hacktoberfest-accepted labels. I would really appreciate it.
