### ISSUE TITLE
Implement a 404 page

### ISSUE THREAD

**Issue by origranot** [origranot/reduced.to#233]
### Description

If you navigate to unknown url we should redirect to a 404 page.

### Screenshots

<img width="458" alt="image" src="https://user-images.githubusercontent.com/48911144/196057527-fb529448-d3e9-4a52-a2af-3f1e2e87c66e.png">

**Comment by kymppi** [comment]
Hey, i can do this tomorrow 😄

**Comment by kymppi** [comment]
Just wanting to clarify, does it have to redirect or could it just show a 404 on that URL?

**Comment by origranot** [comment]
> Just wanting to clarify, does it have to redirect or could it just show a 404 on that URL?

@kymppi Hey 👋 

We need to create a new 404 page and redirect clients to this page.
Thanks for taking this issue, I will assign you to it.

**Comment by kymppi** [comment]
Okay, thanks. Most likely a PR ready in 24 hours :P

**Comment by origranot** [comment]
@kymppi I liked it 🔥 

Thank you so much for your contibution!
