### ISSUE TITLE
Add a rate-limit to prevent a brute-force attack on our server

### ISSUE THREAD

**Issue by origranot** [origranot/reduced.to#235]
### Description

Right now users can call the shortener method how many times they want.
We need to implement a rate-limit on our server, the best practice is by using @nestjs/throttler package.
docs: https://docs.nestjs.com/security/rate-limiting

**Comment by TheLearneer** [comment]
Hi @origranot 👋 

Is it up for grabs?

**Comment by GuillemPM** [comment]
> Hi @origranot 👋
> 
> Is it up for grabs?

For sure, feel free to PR 🎉🚀
