### ISSUE TITLE
day mode color not accurate

### ISSUE THREAD

**Issue by HridoyHazard** [origranot/reduced.to#243]
### Description

in day mode the color of text and shorten button is not good. it's looking very weird. i can fix this. assign this task to me

### Screenshots

![image](https://user-images.githubusercontent.com/71395891/196223656-9d30f6d4-1ef1-45e7-b558-4c45dc8bc03b.png)

**Comment by origranot** [comment]
Go for it!

**Comment by origranot** [comment]
@HridoyHazard Pay attention we just changed the colors in the light mode.
If you still want to offer a change you are welcome to reopen this issue.
Please review our change first.
PR: https://github.com/origranot/reduced.to/pull/244
