### ISSUE TITLE
Alert popup is not floating

### ISSUE THREAD

**Issue by origranot** [origranot/reduced.to#249]
### Description

The alert component is not floating, causing the page to be pushed down.

### Screenshots

Before:
![image](https://user-images.githubusercontent.com/48911144/196429228-fb4ccb89-93e9-4620-91c1-114dd7fb19cc.png)

After:
![image](https://user-images.githubusercontent.com/48911144/196429106-ef52bf90-214c-4a82-98c7-74be2ebe4eed.png)

**Comment by ahmed-sudani** [comment]
I would like to handle this one

**Comment by origranot** [comment]
> I would like to handle this one

Go for it 🚀

**Comment by origranot** [comment]
There is no one working on this issue, feel free to take it 🔥

**Comment by thenishantsapkota** [comment]
Can I try this?

**Comment by origranot** [comment]
> Can I try this?

Go for it!

**Comment by origranot** [comment]
I would prefer to change it to something like this:
![image](https://user-images.githubusercontent.com/48911144/197334268-fb89836c-888d-4a2c-a9cb-854fa724f4eb.png)

**Comment by ccjmne** [comment]
@origranot Hey 👋,

Do you mean that you want it floating, like this...
![image](https://user-images.githubusercontent.com/6822545/197421186-e8e0921a-f54f-45ed-91de-bfd347f98ba9.png)

But also have it take the entire width of the screen, even in Desktop mode?

**Comment by origranot** [comment]
We added a tooltip component, https://github.com/origranot/reduced.to/pull/290
