### ISSUE TITLE
Feature: easily check where the url redirects without opening it

### ISSUE THREAD

**Issue by kymppi** [origranot/reduced.to#250]
### Description

You could add `+` to the end of any generated URL and it would show the URL it's going to redirect to.

### Additional information

I could add this :rocket:

**Comment by GuillemPM** [comment]
That's a good idea, go for it! 🔥

**Comment by kymppi** [comment]
Hey, i currently have some problems trying to get data to the page. Any ideas? I have never done this before :thinking:

**Comment by origranot** [comment]
> Hey, i currently have some problems trying to get data to the page. Any ideas? I have never done this before 🤔

What kind of problems? I would like to get a deeper explanation 👍 

I would like to help if I can 💯

**Comment by kymppi** [comment]
Thanks for asking. Currently i cant figure out a way to pass data into the qwik app, since if i try to make a file named `[...id].tsx` it doesnt seem to be included in the dist/public folder in the backend.

**Comment by kymppi** [comment]
I would need to pass the original url from the database/cache to the qwik app.

**Comment by origranot** [comment]
> I would need to pass the original url from the database/cache to the qwik app.

I am not sure I understood the problem you are facing.
When exactly do you want to add a button to see the original url?
Can you describe the flow of the app with the feature?

**Comment by kymppi** [comment]
I'm trying to create a page where it shows the original URL. I have no idea how to get the original URL to the qwik app. I'm trying not to add a button, but a new page.

The flow:
- User wants to check the original URL
- User goes to <shortened URL>+ for example `https://reduced.to/k79a3+`
- It redirects to `https://reduced.to/preview/k79a3`
- In that page it would show the original url

**Comment by GuillemPM** [comment]
If I understand well, the solution would be adding a new API endpoint in the backend and it should provide the required data.

In your new page in qwik, you have the reduced url. Call the new backend endpoint sending that url.
Backend should search for the original url in the cache and return it as a response.

Then load that data into the page as you want.

**Comment by kymppi** [comment]
That could work. Ill do that for now, but in the future, it could be done so you don't need to make an API call.

**Comment by GuillemPM** [comment]
> That could work. Ill do that for now, but in the future, it could be done so you don't need to make an API call.

It's possible that we split the frontend and backend into different apps, that's why we work with API calls
Thanks!

**Comment by kymppi** [comment]
Wait, I now tried to do it the API request way but I still need to know which URL should I request data about.

**Comment by GuillemPM** [comment]
API endpoints are declared inside the controllers. (check app.controller.ts and shortener.controller.ts).
app.controller.ts is handling requests on `/`
shortener.controller.ts is handling requests on `/api/v1/shortener`

https://docs.nestjs.com/controllers

Since we activated versioning, any controller that you indicate a version will be directly prefixed under /api/v*/yourEndpoint
![image](https://user-images.githubusercontent.com/26607131/196992947-0f686d94-6af8-4f62-86ef-9dab402e6939.png)

![image](https://user-images.githubusercontent.com/26607131/196992852-c58445d4-9f99-4d80-8da0-0793b2f59479.png)

**Comment by kymppi** [comment]
I know, but how does the frontend know which original URL should it request?

**Comment by kymppi** [comment]
I dont think you understand my problem...

**Comment by GuillemPM** [comment]
The original url is linked to the shortened url in the cache module.
If you have the reduced url in the frontend is simple as that:
![image](https://user-images.githubusercontent.com/26607131/196993658-190d1b86-eb6f-4cce-b9cc-c16acfd32059.png)

**Comment by GuillemPM** [comment]
You will need to create a dynamic route for that and handle it
/[slug]

https://qwik.builder.io/qwikcity/routing/route-parameters/#catch-all-routes

**Comment by kymppi** [comment]
> Thanks for asking. Currently i cant figure out a way to pass data into the qwik app, since if i try to make a file named `[...id].tsx` it doesnt seem to be included in the dist/public folder in the backend.

As I said before, I tried that but when I built the website, it was not found in the dist/public.

**Comment by GuillemPM** [comment]
The site is built as SSG, so probably it needs extra config, I didn't check the docs:
https://qwik.builder.io/qwikcity/static-site-generation/static-site-config/

**Comment by GuillemPM** [comment]
Also this: https://qwik.builder.io/qwikcity/static-site-generation/dynamic-routes/

**Comment by kymppi** [comment]
Okay, I checked those links but how am I going to get all the generated links during build time?

**Comment by GuillemPM** [comment]
Yep, good point, actually you would need to get all available urls from cache module, and create one page for each of them (and I don't like that)

So we should think on another approach, or maybe @origranot has any idea on how to solve it.
I don't have much time right now to think about it, but I will later

**Comment by kymppi** [comment]
Okay. Thanks!

**Comment by origranot** [comment]
Why can't we just render it dynamically with an API call?

**Comment by kymppi** [comment]
> I know, but how does the frontend know which original URL should it request?

**Comment by GuillemPM** [comment]
I had an idea, will update later.

**Comment by origranot** [comment]
> > I know, but how does the frontend know which original URL should it request?

You can get the url parameters from request, we can do a preview page with $useResource hook to fetch the original url from the backend.

What do you think?

**Comment by kymppi** [comment]
> > Thanks for asking. Currently i cant figure out a way to pass data into the qwik app, since if i try to make a file named `[...id].tsx` it doesnt seem to be included in the dist/public folder in the backend.
> 
> As I said before, I tried that but when I built the website, it was not found in the dist/public.

Could you please read this conversation

**Comment by origranot** [comment]
> > > Thanks for asking. Currently i cant figure out a way to pass data into the qwik app, since if i try to make a file named `[...id].tsx` it doesnt seem to be included in the dist/public folder in the backend.
> 
> > 
> 
> > As I said before, I tried that but when I built the website, it was not found in the dist/public.
> 
> 
> 
> Could you please read this conversation

This is a one way of doing it.
We can do a simple preview page and pass in the url the reducedUrl In order to dynamically generate the preview page..

**Comment by origranot** [comment]
Obviously I prefer using your way, I will think about something 🤔

**Comment by GuillemPM** [comment]
I have 2 approaches + 1 that I need to investigate if it's possible.

Approach 1: 

Backend:
Redirects from the received path (51hwgw1+) to /details?id=51hwgw1

Frontend: 
We have a static defined page. Ex: details. Will show the details of the url received by param in the url
Details?id=51hwgw1

It now makes an api call to backend to retrieve the related data.

Approach 2:
We separate the frontend and backend into independent apps.

Approach 3:
Investigate if it's possible to mix SSR and SSG when we are serving Qwik from the backend, and let me guess, it's not (which sends me to approach 2)
