### ISSUE TITLE
Easy-to-remember URLs

### ISSUE THREAD

**Issue by GuillemPM** [origranot/reduced.to#251]
### Description

We know short urls are cool, but its almost impossible to remember them, isn't it?

My idea is to add an option for the user, to create easy to remember urls, what does **Easy to remember** means?
 - It means anything that the user could write by himself or even say to another person without saving the url in a note.

Example:
URL to reduce: https://somelongurl.com/verylongdatasubpageorwhateveridontknow
Easy to remember url: https://reduced.to/dog-cat-fly

A combination of 3 short words.
You could say to someone: Yey! visit dog cat fly to see that great article about how to develop a shortener url app.

**Comment by origranot** [comment]
That's a great idea 🔥

**Comment by codingis4noobs2** [comment]
@origranot I Can do it assign me

**Comment by theGeekyLad** [comment]
I'd love to contribute to this! If no one has picked it up yet, I'd be happy if it can be assigned to me.

**Comment by GuillemPM** [comment]
Hey! Thanks, right now this issue is on hold, I'll update when it is available to work on
