### ISSUE TITLE
Seperate the project into 2 different applications

### ISSUE THREAD

**Issue by origranot** [origranot/reduced.to#265]
### Description

Currently we are using NestJS with SSG.
Our goal is to separate our project into 2 different apps, front and back.

**Comment by origranot** [comment]
F**K Yea https://github.com/origranot/reduced.to/pull/278

**Comment by GuillemPM** [comment]
A lot of effort here, never forget those nights till 5am solving unexpected bugs😅🤣

**Comment by origranot** [comment]
> A lot of effort here, never forget those nights till 5am solving unexpected bugs😅🤣

At least we got it 🥇 💯
