### ISSUE TITLE
Spelling correction

### ISSUE THREAD

**Issue by DEV-YJY** [origranot/reduced.to#266]
### What would you like to share?

![image](https://user-images.githubusercontent.com/86042155/197283880-027d4764-b029-429d-bdff-6504e0b11a94.png)
I can correct the spelling above

**Comment by origranot** [comment]
Hey @DEV-YJY 👋 ,

What is your suggestion?

**Comment by DEV-YJY** [comment]
It is a very simple fix
'bellow' should be 'below' : >

**Comment by this-mkhy** [comment]
@DEV-YJY Done

**Comment by origranot** [comment]
> It is a very simple fix 'bellow' should be 'below' : >

Go for it.

**Comment by origranot** [comment]
@this-mkhy Can you also change it on the docs?
