### ISSUE TITLE
add button to share on twitter

### ISSUE THREAD

**Issue by dav-q** [origranot/reduced.to#270]
### Description

The idea is to add a twitter button to be able to share the generated short url using the url provided by twitter (https://twitter.com/share?url=shortedUrl)
something like the attached image.

### Screenshots

![image](https://user-images.githubusercontent.com/50281001/197365743-b20f9775-5159-466c-a5d4-61cb0e8672fb.png)
![image](https://user-images.githubusercontent.com/50281001/197365894-520ddae3-58e7-4120-916c-deadf15d7efa.png)

### Additional information

If you agree assign me and I can work on it

**Comment by origranot** [comment]
Hey, That's looks great!

I would add a brief explanation on the post and not just pasting the short url.

Something like this:
```suggestion
My url has just reduced!

Check out: ${URL}
```

**Comment by dav-q** [comment]
A brief description and a couple of hashtags are added in the publication preview.
![preview](https://user-images.githubusercontent.com/50281001/197414775-058e13a6-a4ff-4142-a18c-78f717c5c4c0.gif)

**Comment by origranot** [comment]
Done https://github.com/origranot/reduced.to/pull/277
