### ISSUE TITLE
Shortened URL cannot be used as very long URL

### ISSUE THREAD

**Issue by nirajpdn** [origranot/reduced.to#271]
### Description

I have a long domain url `https://www.restaurant-indien-kamran.fr/`.
It is then shortened to `https://reduced.to/kubz1`.

Now i can use `https://reduced.to/kubz1` as a very long url which will shortened to `https://reduced.to/liz06`.

I can do it many times as i can. Redirection is done in all the shortened url which will cost the performance of the system. 
So `RegEx` can be used to avoid reduced url as a input in very long url.

 Or

Use one redirection when using `https://reduced.to/liz06` then it should redirect to main url `https://www.restaurant-indien-kamran.fr`

### Screenshots

<img width="571" alt="Screen Shot 2022-10-23 at 08 02 48" src="https://user-images.githubusercontent.com/59108522/197369911-7b6726aa-55ce-43e4-9b15-2540effcc1b5.png">

**Comment by origranot** [comment]
You are correct, we can check if the original url is not part of our domain (reduced.to).
What do you think about this solution?

**Comment by origranot** [comment]
@nirajpdn Do you want to add this check?

**Comment by Riyadutt** [comment]
I have raised a PR to fix this issue, there are a few alternate approaches as well, but I feel this will do just fine.

**Comment by Riyadutt** [comment]
@origranot can you have a look at it.

**Comment by origranot** [comment]
> @origranot can you have a look at it.

@Riyadutt I left comments on the pr.

**Comment by Riyadutt** [comment]
will send out the fix by tonight.

**Comment by xarielah** [comment]
#350 Added a backend block for that by using RegEx. No changed on the frontend.

**Comment by origranot** [comment]
Closed #350
