### ISSUE TITLE
Bug: Android keyboard hides input fields

### ISSUE THREAD

**Issue by devXprite** [origranot/reduced.to#272]
### Description

Android keyboard hides input fields when start typing.

### Screenshots

https://user-images.githubusercontent.com/80192140/197387905-c2721d71-1565-49a6-a17d-24d474f6d9de.mp4

### Additional information

I want to work on this issue

**Comment by origranot** [comment]
@devXprite 👋 

Go ahead :)

**Comment by devXprite** [comment]
> @devXprite 👋
> 
> What is the resolution you are using?
> 
> You are welcome to fix it 😄

360 × 760 px
