### ISSUE TITLE
Header Should look much attractive

### ISSUE THREAD

**Issue by kushaljgec2025** [origranot/reduced.to#285]
### Description

Header is not so attractive . I want to do some ui work in header logo . so please assign me this. 

### Screenshots

![image](https://user-images.githubusercontent.com/108950724/197580386-f3372eb8-5531-4651-906d-d11f72677f40.png)

**Comment by origranot** [comment]
@kushaljgec2025 Why did you closed this issue?

If you have an idea for our logo, go for it 🚀
