### ISSUE TITLE
Count of URL clicks

### ISSUE THREAD

**Issue by TanmayPatil105** [origranot/reduced.to#286]
### Description

There should be a feature to get the count of the link clicks we have shortened.
Whenever a user clicks on the `SHORTENED_URL`, the count should increase.

**Comment by origranot** [comment]
@TanmayPatil105 👋 

Thank you for the suggestion! 

We already have an open issue about it. https://github.com/origranot/reduced.to/issues/101
This is in our roadmap, we are working on it 🚀
