### ISSUE TITLE
Style the tooltip component

### ISSUE THREAD

**Issue by origranot** [origranot/reduced.to#292]
### Description

Our tooltip component need some style to fit our dark/light mode 🔥 

### Screenshots

<img width="1128" alt="image" src="https://user-images.githubusercontent.com/48911144/197888054-7dfaf73a-412e-4bbc-af7b-d5a793e59a19.png">
<img width="1128" alt="image" src="https://user-images.githubusercontent.com/48911144/197888107-1ec11214-32d9-47be-916c-103e996b9647.png">

### Additional information

The tooltip color should be change according to site theme (dark / light).

Go for it 🚀

**Comment by deepaksuthar40128** [comment]
Can you assign it to me

**Comment by Riyadutt** [comment]
Assign it to me please, I have raised a PR with the fix.

**Comment by prabhleenn** [comment]
Hey ! I would love to work on this by making my first Hacktoberfest submission.
It would be great if you assign me this.

**Comment by amittri1025** [comment]
@Riyadutt did you fixed it ?

**Comment by GuillemPM** [comment]
Closing for #295
