### ISSUE TITLE
Add a Social Media Preview Image

### ISSUE THREAD

**Issue by devXprite** [origranot/reduced.to#296]
### Description

In order to have preview on Twitter, we need to specify a "twitter:card" with  "twitter:image"

### Additional information

I want to work on this issue

**Comment by origranot** [comment]
@devXprite Thank you for the suggestion!
We already have a metadata from twitter.

**Comment by origranot** [comment]
> Actually i am talking about "twitter:image" which is use with "twitter:card" .
> 
> ### Current :
> ![IMG_20221026_190650](https://user-images.githubusercontent.com/80192140/198040706-a2968890-0eee-4ed3-8e49-54df5171c469.jpg)
> 
> https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/markup

First we need a unique icon :)
https://github.com/origranot/reduced.to/issues/297
