### ISSUE TITLE
Design a custom icon / favicon for our app

### ISSUE THREAD

**Issue by origranot** [origranot/reduced.to#297]
### What would you like to share?

Hey all 👋,

We would like to design a creative icon to our website.
Don't be afraid to use your imagination, let's go 🚀

**Comment by origranot** [comment]
> Hello, I can try and make a few ideas for the icon, and also, is this hacktober accepted? :D

Go for it!

All the issues are hacktoberfest accepted 🤩

**Comment by owengaspard** [comment]
I have designed a new favicon for the app. Please see PR #298 when you have a chance.

**Comment by SaxenaAnushka102** [comment]
Hello @origranot! I'd like to contribute, could you please assign this to me?

**Comment by Manohar-mj** [comment]
Hello I would like to contribute please assign me

**Comment by origranot** [comment]
@SaxenaAnushka102 @Manohar-mj You are welcome to open a pr about it. :)

**Comment by komalioruganti** [comment]
I can make a favicon. Can you assign me this issue

**Comment by komalioruganti** [comment]
I can make a favicon that matches the name of the website a little more

**Comment by origranot** [comment]
Done https://github.com/origranot/reduced.to/pull/335
