### ISSUE TITLE
added a Product Suggestions doc & pdf files

### ISSUE THREAD

**Issue by tapaskhanijo** [origranot/reduced.to#303]
### Description

I felt like adding a few product suggestions in the form of a brief doc, so raised a pull request with the same:) 

**NOTE:** _these suggestions are based on my personal preferences/experiences, which I would love to see built-in any product like this:)_

**Comment by origranot** [comment]
Go for it, we have a roadmap in our readme.

**Comment by tapaskhanijo** [comment]
> Go for it, we have a roadmap in our readme.

done!!

**Comment by origranot** [comment]
Please don't push files to our project.

If you have any suggestion you can create an issue about it :)
