### ISSUE TITLE
Product Functions~ Suggestions

### ISSUE THREAD

**Issue by tapaskhanijo** [origranot/reduced.to#306]
### Description

**Product Suggestions~ reduced.to**

**NOTE:** these suggestions are based on my personal preferences/experiences, which I would love to see built-in any product like this:)

**1.	Ownership~** a brief about the creators, the idea, the problem and how it is solving, so that people can get a brief sense of the product.

**2.	Testimonials~** popping up decent reviews by people, who’ve used the product, in order to boost the authenticity of the product.

**3.	Statistics~** depicting visually on the website:

•	what kind of links people are shortening?
•	how many folks are using the platform on daily basis?
•	during which time people are surfing the platform most?

**4.	Icons~** instead of hovering over the icons, adding bars with the functions (Copy, Open in New Tab, QR Code) written over it. It’ll be easy to navigate.

**5.	How to?~**  a short video demo with a tiny blurb on “how to use the tool” to make best out of it!

**6.	Future~** inculcating a brief of the updates which are in pipeline and are going to be live soon! 

If this sounds good, would be happy to add it to the README.md and raise a pull request! Thanks:)

**Comment by origranot** [comment]
@tapaskhanijo Thank you for your contribute!
I think it will fit better at the discussion tab.
