### ISSUE TITLE
Use SVG logo

### ISSUE THREAD

**Issue by Akshu-on-github** [origranot/reduced.to#320]
### Description

Using a `.png` image for a logo is not recommended because:
- It can take up a lot of space
- It is pixelated when zooming in
- It is not easily customizable

Instead, I'd suggest using an SVG - I propose that I do the following:
- Make an SVG of the logo
- Add it to the following files:
  - Readme.md
  - public/logo.png

### Screenshots

| Description | Screenshot |
|-|-|
| Screenshot of logo | ![image](https://user-images.githubusercontent.com/61582763/199002435-dad85707-3934-4a7a-8e19-96b03dc08e21.png) |
| Screenshot of logo when zoomed in<br><br>Text provided below for reference for pixelation | ![image](https://user-images.githubusercontent.com/61582763/199002571-07c50491-0a98-4aee-9783-9be7c95611f4.png) |

### Additional information

I'd like to update the link to the readme.md to a link to the logo asset.

If all's well, I'll start working on this Issue

**Comment by GuillemPM** [comment]
Perfect, we had it in our backlog, but we don't have time to do it, it would be really nice if you work on it. 🔥

**Comment by Akshu-on-github** [comment]
Awesome! Here's what I've made (in png because markdown doesn't support SVG):

<img src="https://user-images.githubusercontent.com/61582763/199013316-e52cf852-5ef9-401d-b0e0-5308283400d4.png" width=75%>

If possible, could you confirm what font and weight were used? I've taken a guess and used Sinkin Sans Semibold (600) - let me know if I should change this

**Comment by Akshu-on-github** [comment]
Also, could you please tell me what I should modify on the frontend? I'm not familiar with Qwik App, but I'd be happy to follow any directions given

**Comment by origranot** [comment]
> Also, could you please tell me what I should modify on the frontend? I'm not familiar with Qwik App, but I'd be happy to follow any directions given

@Akshu-on-github 
You can just change the reference to ```logo.png``` at```index.ts```.
Also don't forget to change readme also 🚀

**Comment by origranot** [comment]
@Akshu-on-github Are you still working on this issue?

**Comment by Akshu-on-github** [comment]
Hey there,
Must have missed the last message - will get this done asap!

**Comment by Akshu-on-github** [comment]
I'm a bit confused about where the path to the logo in `index.ts` is - to confirm, `reduced.to/frontend/src/utils/index.ts` is the file I should be focussing on, right?

**Comment by origranot** [comment]
> I'm a bit confused about where the path to the logo in `index.ts` is - to confirm, `reduced.to/frontend/src/utils/index.ts` is the file I should be focussing on, right?

It should be under ```reduced.to/frontend/src/routes/index.ts```

**Comment by xarielah** [comment]
Hey all!
I tackled this issue with a pull req, you might take a look 💯

**Comment by origranot** [comment]
> Hey all! I tackled this issue with a pull req, you might take a look 💯

Thank you for the PR!

Closed https://github.com/origranot/reduced.to/pull/343
