### ISSUE TITLE
make the site more accessible

### ISSUE THREAD

**Issue by jessej-samuel** [origranot/reduced.to#328]
### Description

I think the site will be more accessible if on clicking `/` the URL input gets focused.

Ex: https://www.youtube.com/

### Additional information

If this is approved, I am willing to work on this! Also, I'm open to suggestions on changes!

**Comment by origranot** [comment]
Hey, can you please give a deeper explanation about the feature?

**Comment by jessej-samuel** [comment]
Ok, so when you load the page the most likely action you want to do is enter a URL and generate a shortened link.

Let's take the Youtube homepage for example. Most users just wanna search for a term to search something.  Having the search box focus on clicking `/` so that they can start typing without using the mouse actually improves the user experience on the site. This is not just a YT thing. It's there on many sites now. Developers use this feature the most (probably) 

Why try clicking `/` on this page ;) 

The point is it saves the time for using the mouse to focus the textbox before typing in the phrase :)

**Comment by origranot** [comment]
Oh, I didn't even knew it 🤣 

This is a cool idea, go for it!

**Comment by jessej-samuel** [comment]
Also, I can just start work on the master branch ryt?

**Comment by origranot** [comment]
> Also, I can just start work on the master branch ryt?

Yes, fork and create a pull request 🚀

**Comment by origranot** [comment]
@jessej-samuel Are you still working on this issue?

**Comment by xarielah** [comment]
Hey all!
I sent a PR right now #345 I'm available for any changes required ;)

**Comment by origranot** [comment]
https://github.com/origranot/reduced.to/pull/349
