### ISSUE TITLE
Remove fonts.googleapis.com and cdnjs.cloudflare.com

### ISSUE THREAD

**Issue by Dominion0815** [origranot/reduced.to#337]
### Description

Hi,

first at all it is a very nice project and I like it.
But external links to cloudflare and google are not my favorits. Is it possible to store such files local?

thx in advanced
dominion

**Comment by origranot** [comment]
Hey @Dominion0815,

I personally think that CDN are better than store the files locally.
I am talking mostly about average load time and security aspects.

Thank you for your issue :)
