### ISSUE TITLE
Question about DATABASE_URL

### ISSUE THREAD

**Issue by Dominion0815** [origranot/reduced.to#338]
### What would you like to share?

Hi,

I used the docker version and I've set DATABASE_URL to a docker located postgres db.
But I don't see any entries in the database, where are the short urls stored?

greetings
dominion

**Comment by origranot** [comment]
Hey @Dominion0815 👋,

At the moment we are developing the authentication system (using Prisma and Postgres).
DATABASE_URL is used by Prisma to access Postgres.

Short urls are stored in-mem at backend instance by the cache module.

**Comment by Dominion0815** [comment]
thx !

If I understand correctly, there is currently no permanent storage of the short URLs. Will the short URLs be able to be stored on disk at some point and will they all be lost during the changeover?

**Comment by origranot** [comment]
> thx !
> 
> If I understand correctly, there is currently no permanent storage of the short URLs. Will the short URLs be able to be stored on disk at some point and will they all be lost during the changeover?

At the moment the URLs are not permeant, they will be permanent as soon as we finish the authentication.
