### ISSUE TITLE
Redirect to origin URL

### ISSUE THREAD

**Issue by Ali-Amechghal** [origranot/reduced.to#342]
### Description

Hey,

Meaby it will be more efficient to return an HTTP 301 so the browser will handle the redirect instead of using window.location in the front-end

Cheers

**Comment by origranot** [comment]
Hey @Ali-Amechghal,

It's a good idea, I think we still need to think about all the edge cases.
A 301 response code will cache the redirected website at client cache, What will happen if we change the redirect on our side?

**Comment by Ali-Amechghal** [comment]
Hey @origranot 
Hope you doing well,

i didn't get what kind of change we need, you mean the user can change the origin url once created ?
for the second part, do you mean to display the preview before redirecting to the origin ? what about displaying it when to user create the short link ?

Thanks

**Comment by origranot** [comment]
@Ali-Amechghal 
Yes, if the user change origin url  after it has been used. it won't work until the browser clear the cache.

For the second part I did think about some preview before we redirect to origin (To everyone and not specially for the creator).

For those cases the 301 redirect can be problematic..
