### ISSUE TITLE
Add script to create appropriate tables on db on dev-env

### ISSUE THREAD

**Issue by xarielah** [origranot/reduced.to#351]
### What would you like to share?

Prisma requires the needed Schemas from code to exist (when working on signup / signin branch).
Need to add a script to **package.json**:
`"dev:migration": "prisma migrate reset"`

@origranot

**Comment by xarielah** [comment]
Solution from GH issues on Prisma
https://github.com/prisma/prisma/issues/10633

**Comment by origranot** [comment]
We talked via Discord 👍
