### ISSUE TITLE
[DOCS] API 

### ISSUE THREAD

**Issue by Gabbalo** [origranot/reduced.to#375]
### Description

I wasn't able to find a documentation on the API, yet there is an ENV to configure an API domain, so I assume, there IS an API available. Can someone maybe provide some sort of documentation, on how to use the API?

**Comment by origranot** [comment]
Hey @Gabbalo,

Currently there isn't any official API for reduced.to.
You are welcome to create some documents about it if you want :)

**Comment by ronnahmias** [comment]
@origranot
Hi, 
You mean creating a swagger for the API?

**Comment by origranot** [comment]
> @origranot Hi, You mean creating a swagger for the API?

@ronnahmias There is an ongoing PR we are working on (https://github.com/origranot/reduced.to/pull/404).
I don't think swagger is needed, we will definitely need some help with maintaining our docs.

**Comment by talperets** [comment]
Hi, please assign me for this issue

**Comment by origranot** [comment]
Hey @talperets how it's going?

**Comment by talperets** [comment]
Hey @origranot , I had a lot of freelance projects on my plate but I will send a new pull request in the next two days

**Comment by origranot** [comment]
Done in https://github.com/origranot/reduced.to/pull/404
