### ISSUE TITLE
[DOCS] Improve the installation part

### ISSUE THREAD

**Issue by origranot** [origranot/reduced.to#380]
### Description

- Explain about Prisma, which commands we should run? (when?)
- Improve the docker section, explain about Redis, Postgres and etc..

**Comment by amittri1025** [comment]
Hello @origranot can you please tell me how the loading part was implemented, like when we click on a button , there is a loading line on the top of the page.
and also when we click on shorten url , there is sticker pop up.

**Comment by origranot** [comment]
> Hello @origranot can you please tell me how the loading part was implemented, like when we click on a button , there is a loading line on the top of the page. and also when we click on shorten url , there is sticker pop up.

I don't understand which loading line and which pop up are you talking about.
Can you please be more specific?
