### ISSUE TITLE
Make platform depend url

### ISSUE THREAD

**Issue by elihaidv** [origranot/reduced.to#384]
### Description

It will be great if I could enter different URLs for different platforms.
So the system will check the agent and redirect me to the correct url.

For example I want to create a link for my app. 
But I have an Android app and an IOS app.
I want the link will open the Google Store and the App Store respectively.
In addition maybe I want on desktop to redirect to the website.
Also I want to open the app itself, if it already installed on my device.

**Comment by origranot** [comment]
Hey @elihaidv,

Thank you for your suggestions, this is awesome!
We first need to implement some basic dashboard features.

I will defiantly keep this issue open and in my mind 💯
