### ISSUE TITLE
Allow Registered Users to Set Custom Expiration Times for Shortened URLs

### ISSUE THREAD

**Issue by achiyahb** [origranot/reduced.to#385]
### Description

Right now, all shortened URLs have the same expiration time.
I suggest creating an interface that allows registered users to choose their preferred TTL.

### Additional information

I am interested in working on this task.

**Comment by origranot** [comment]
Hey @achiyahb, thank you so much for your suggestion.
This sounds very cool. are you planning to implement this?

**Comment by achiyahb** [comment]
Yes, I am planning to implement this feature.

**Comment by origranot** [comment]
> Yes, I am planning to implement this feature.

Great!

I assigned you to this issue 💯
