### ISSUE TITLE
Can't register 

### ISSUE THREAD

**Issue by mariushosting** [origranot/reduced.to#388]
### Description

Everytime I try to register using the Login button
I get the following error on logs:

Server started at port 5000
Lo [Error]: Cross-site POST form submissions are forbidden
    at Object.error (file:///app/server/entry.express.mjs:19:4915)
    at xa (file:///app/server/entry.express.mjs:19:960)
    at Object.f [as next] (file:///app/server/entry.express.mjs:19:3764)
    at Ia (file:///app/server/entry.express.mjs:19:6468)
    at za (file:///app/server/entry.express.mjs:19:6424)
    at Ua (file:///app/server/entry.express.mjs:19:8192)
    at async router (file:///app/server/entry.express.mjs:302:2854) {
  status: 403
}

**Comment by mariushosting** [comment]
> Hey @mariushosting,
> 
> How did you try to run the front and backend?
> 
> Using docker compose?

[reduced issue.txt](https://github.com/origranot/reduced.to/files/11508161/reduced.issue.txt)

**Comment by origranot** [comment]
> > Hey @mariushosting,
> 
> > 
> 
> > How did you try to run the front and backend?
> 
> > 
> 
> > Using docker compose?
> 
> 
> 
> [reduced issue.txt](https://github.com/origranot/reduced.to/files/11508161/reduced.issue.txt)
> 
> 
> 
> This is the compose. I can access the frontend but can't register
> 
> 

I can see why it's happening.

I changed this behavior to work in the production Docker file but forgot to change in the regular Docker file.

We need to pass ORIGIN variable when starting Qwik.

https://github.com/BuilderIO/qwik/issues/3325

Do you want to create a PR for it?

**Comment by mariushosting** [comment]
Thanks for checking! So You will update the docker?

**Comment by mariushosting** [comment]
So I can access it...but can't register https://reduced.mariushosting.synology.me/ due to this issue.

**Comment by origranot** [comment]
> Thanks for checking! So You will update the docker?
> 
> 

I can do it, I thought someone else might what to grab that issue 💯

**Comment by origranot** [comment]
> Can I be assigned on this?

Go for it!

**Comment by origranot** [comment]
Hey, I did a little changes in the docker-compose file.
Added some explanation in the README about local setup with docker-compose.
The issue should be solved.

**Comment by mariushosting** [comment]
> Hey, I did some changes in the docker-compose file. Added explanation under the docker-compose local setup. The issue should be solved.

Can you please point me to the explanation? I did not find it in the compose.

Thank you!

**Comment by origranot** [comment]
> > Hey, I did some changes in the docker-compose file. Added explanation under the docker-compose local setup. The issue should be solved.
> 
> Can you please point me to the explanation? I did not find it in the compose.
> 
> Thank you!

Sure, if you want to run it with docker-compose for local development there is a [note](https://github.com/origranot/reduced.to#-docker-compose).
If you want to run it in "production" you can use the docker compose under the /docker/deployment folder.
