### ISSUE TITLE
Split and organize our workflows 

### ISSUE THREAD

**Issue by origranot** [origranot/reduced.to#389]
### What would you like to share?

Hey, currently all the jobs are running on the CI workflow. (build, tests and linter).
I suppose we split the workflow into smaller workflows.

**Comment by hritikchaudhary** [comment]
Hi @origranot, I was looking at the CI workflow and I can bifurcate the workflow into three smaller workflows for lint, build and tests but I have a doubt regarding the install npm dependencies as it'll need to be run for all the workflows (time will be increased)... is that acceptable?
or there needs to be some type of caching so once downloaded we can reuse the node_modules across the workflows?

**Comment by origranot** [comment]
> Hi @origranot, I was looking at the CI workflow and I can bifurcate the workflow into three smaller workflows for lint, build and tests but I have a doubt regarding the install npm dependencies as it'll need to be run for all the workflows (time will be increased)... is that acceptable?
> 
> or there needs to be some type of caching so once downloaded we can reuse the node_modules across the workflows?

Hey @hritikchaudhary,

That's a good point.
I think we can use actions/cache to solve this issue, what do you think?

**Comment by hritikchaudhary** [comment]
@origranot yes we can use actions/cache. I'll check both cause i just took a look at past workflow runs and on average it's 90s, and only three new workflow are needed.. so if its an overkill then will simply separate the stages into separate workflows.

**Comment by origranot** [comment]
> @origranot yes we can use actions/cache. I'll check both cause i just took a look at past workflow runs and on average it's 90s, and only three new workflow are needed.. so if its an overkill then will simply separate the stages into separate workflows.

Sounds good 💯

**Comment by fruch** [comment]
@origranot what's the gain of splitting them ?

(I might guess some reasons)

**Comment by origranot** [comment]
Hey @fruch,

When we split workflows we have better isolation and independence of tasks, makes it easier to troubleshoot and debug problems.
Also we can run multiple smaller workflows in parallel, which can significantly reduce the overall build and test time.
And the best part is if a specific stage fails, you can rerun only the affected workflow instead of re-executing the entire CI process.

**Comment by nati-elmaliach** [comment]
Hey, i would like to work on it, please assign it to me :)

**Comment by fruch** [comment]
> Hey @fruch,
> 
> When we split workflows we have better isolation and independence of tasks, makes it easier to troubleshoot and debug problems.
> Also we can run multiple smaller workflows in parallel, which can significantly reduce the overall build and test time.
> And the best part is if a specific stage fails, you can rerun only the affected workflow instead of re-executing the entire CI process.

That's the GitHub sales pitch :)

I would argue, that for less than 2min flows it's quite an over complex.

But yes it's has high educational value 😃

**Comment by hritikchaudhary** [comment]
> Hey, i would like to work on it, please assign it to me :)

Hi @nati-elmaliach sorry if my comments were not clear but my intention was to work on it.. and i already did. if you haven't started your work can i take this?.. if you have started not a problem, you can continue to work on it.
