### ISSUE TITLE
Users table (Admin Dashboard)

### ISSUE THREAD

**Issue by origranot** [origranot/reduced.to#393]
### Description

**When you are working on this feature make sure you are giving yourself an ADMIN role in the database**

Currently we have an empty admin dashboard.
I think we should implement some components, we can start with a table of the registered users.

- I think we should use Tanstack table (vanilla) and implement it in Qwik.
- Also make sure to use DaisyUI (https://daisyui.com/components/table/) 💯 

### Screenshots

![image](https://github.com/origranot/reduced.to/assets/48911144/86434966-8c73-4a12-83f8-14d4e37e44b7)

### Additional information

Tanstack table - https://tanstack.com/table/v8/docs/adapters/vanilla

**Comment by Darkmift** [comment]
do you have any particular table features you want in mind?
which columns you want to show?

**Comment by origranot** [comment]
> do you have any particular table features you want in mind? which columns you want to show?

I think a basic table would work.
Basic table should include name, email, role, etc..

**Comment by Darkmift** [comment]
I'll take it on

**Comment by coder-bat** [comment]
hey @origranot , can I work on this?

**Comment by kareemmahlees** [comment]
Hi @origranot , would like to help, could you assign it to me?

**Comment by origranot** [comment]
> Hi @origranot , would like to help, could you assign it to me?

Hey @kareemmahlees!

Go for it, you can use tanstack headless ui table for it.
Make sure you are implementing a server side pagination for that.

Let me know if I can help you with anything 💯
