### ISSUE TITLE
Add expiration time dropdown in the input url component

### ISSUE THREAD

**Issue by origranot** [origranot/reduced.to#394]
### Description

Hey, for the new feature made by @achiyahb (https://github.com/origranot/reduced.to/pull/391)
The implementation for the front-end should be in the ```shortener-input.tsx``` component.

### Screenshots

![image](https://github.com/origranot/reduced.to/assets/48911144/10b84178-09ea-4f2b-bf8e-4baade794324)

### Additional information

The dropdown values should be able to loaded dynamically.

**Comment by achiyahb** [comment]
Maybe we should change this sketch to use date string? (not an enum)

**Comment by dlibis** [comment]
@origranot i would like to take this issue

**Comment by origranot** [comment]
> @origranot i would like to take this issue

Go for it! 😀

**Comment by origranot** [comment]
Done https://github.com/origranot/reduced.to/pull/400
