### ISSUE TITLE
Upgrade DaisyUI to the new major release

### ISSUE THREAD

**Issue by origranot** [origranot/reduced.to#401]
### What would you like to share?

DaisyUI just released a new major version (3.0.0): https://daisyui.com/

We should upgrade our frontend version (2.51.5) to use the new version.
There are some breaking changes, make sure to check the changelog (https://daisyui.com/docs/changelog/)

**Comment by izdotnet** [comment]
Submitted a pull request to address this issue.

**Comment by origranot** [comment]
[Closed https://github.com/origranot/reduced.to/pull/413](https://github.com/origranot/reduced.to/pull/413)

**Comment by origranot** [comment]
@izdotnet Hey!

Unfortunately I had to revert to the old DaisyUI version because the new DaisyUI is broken.
I came across some weird issues, I think we should wait a bit for more stable version.

**Comment by izdotnet** [comment]
> @izdotnet Hey!
> 
> Unfortunately I had to revert to the old DaisyUI version because I came across some weird issues. I think we should wait for some new releases or at least for a much more stable version.

I did some thorough testing, and I couldn't replicate any bugs on my end. 

It's worth it to wait for a more stable version though.

**Comment by origranot** [comment]
@izdotnet It looks that DaisyUI became more stable.
Do you want to try update it?

**Comment by saku1331** [comment]
I wish to work on this issue. Kindly assign me this.

**Comment by origranot** [comment]
> I wish to work on this issue. Kindly assign me this.

@saku1331 
Alight, I assigned you to it.
Please make sure to see the old PR https://github.com/origranot/reduced.to/pull/413
I reverted it because the new version of DaisyUI wasn't stable at the time.

**Comment by origranot** [comment]
@saku1331 Any updates regarding to this PR?
