### ISSUE TITLE
Add URLs ui

### ISSUE THREAD

**Issue by achiyahb** [origranot/reduced.to#406]
### Description

It would be great if we could add a URLs UI for registered users. In this UI, they will see the URLs they have created. This UI will serve as the infrastructure for new features such as editing the URLs, removing them, and accessing analytics for their URLs.

### Additional information

I would like to work on the backend in this feature.

**Comment by origranot** [comment]
Go for it 🚀 !

**Comment by 0xSaksham** [comment]
@origranot I can implement the front page of this. Should I start working?

**Comment by origranot** [comment]
@0xSaksham go for it!

I thought we can do some kind of Table component for this.
This table component should be generic.

There is an unfinished PR you can take inspiration from: https://github.com/origranot/reduced.to/pull/396

**Comment by 0xSaksham** [comment]
Hi, I was busy with on-campus interviews. I'll start working on it now.

**Comment by origranot** [comment]
> Hi, I was busy with on-campus interviews. I'll start working on it now.
> 
> 

Alright. I started work on it in a separate branch.

You are more than welcome to check it out and continue it 💪

I will let you handle this issue champ 👑

**Comment by 0xSaksham** [comment]
@origranot Thank sir.

**Comment by origranot** [comment]
Fixed in https://github.com/origranot/reduced.to/pull/581
