### ISSUE TITLE
Add timeout for the resend verification email button

### ISSUE THREAD

**Issue by origranot** [origranot/reduced.to#412]
### Description

Currently when new users register to the app they are requested to verify their email.
We don't want users to instantly click the button, we need to add a countdown for the button appearance after register.
Make sure to use DaisyUI countdown component: https://v2.daisyui.com/components/countdown/

### Screenshots

<img width="541" alt="image" src="https://github.com/origranot/reduced.to/assets/48911144/397c3ac3-3106-44cf-81e7-cdbc8dbce650">

**Comment by maha885** [comment]
I have a question that where should be countdown button placed after registration.

**Comment by origranot** [comment]
> I have a question that where should be countdown button placed after registration.

Hey @maha885 

The countdown should be instead of the "resend verification email" text.

In the verify page.

**Comment by maha885** [comment]
Design will be simple or any typography needed ?
What is the start time of countdown?

**Comment by origranot** [comment]
> Design will be simple or any typography needed ?
> 
> What is the start time of countdown?

You should use the daisyui components for it.

The countdown should be passed as a prop, 60 seconds sounds good to me.

**Comment by origranot** [comment]
@maha885 How it's going champ?

**Comment by maha885** [comment]
Hi, I am facing some issues while running it , that's may be ide issue. I am working on it.

**Comment by origranot** [comment]
> Hi, I am facing some issues while running it , that's may be ide issue. I am working on it.

No problem, if you need a hand I am here.

**Comment by origranot** [comment]
@maha885 Hey, are you still working on that issue?

**Comment by mahi25soni** [comment]
@origranot Can I work on this

**Comment by origranot** [comment]
> @origranot Can I work on this
> 
> 

Sounds good, go for it! 🤩

**Comment by mahi25soni** [comment]
Dude I have used this from daisyui
                    <span class="countdown">
                      <span style={`--value: ${countdownValue.value}`}></span>
                    </span>
                    
And for taking time as useEffect, I have done that.

` const countdownValue = useSignal<number>(60);
  const startCountdown = $(() => {
    if (countdownValue.value > 0) {
      setTimeout(() => {
        countdownValue.value--;
        startCountdown(); // Recursive call to continue countdown
      }, 1000);
    }
  });

  useVisibleTask$(() => {
    if (!store.loading && !store.isVerified) {
      startCountdown(); // Start the countdown when the component becomes visible
    }
    authorizedFetch(`${process.env.CLIENTSIDE_API_DOMAIN}/api/v1/auth/verified`).then(async (response) => {
      const { verified } = await response.json();
      store.isVerified = verified;
      store.loading = false;
    });`

But getting error as "Internal server error: Cannot access 'startCountdown' before initialization" , and since this is a new framework, there isn't anything related to this error

**Comment by origranot** [comment]
> Dude I have used this from daisyui <span style={`--value: ${countdownValue.value}`}>
> 
> And for taking time as useEffect, I have done that.
> 
> ` const countdownValue = useSignal(60); const startCountdown = $(() => { if (countdownValue.value > 0) { setTimeout(() => { countdownValue.value--; startCountdown(); // Recursive call to continue countdown }, 1000); } });
> 
> useVisibleTask$(() => { if (!store.loading && !store.isVerified) { startCountdown(); // Start the countdown when the component becomes visible } authorizedFetch(`${process.env.CLIENTSIDE_API_DOMAIN}/api/v1/auth/verified`).then(async (response) => { const { verified } = await response.json(); store.isVerified = verified; store.loading = false; });`
> 
> But getting error as "Internal server error: Cannot access 'startCountdown' before initialization" , and since this is a new framework, there isn't anything related to this error

@maha885 Hey,
I can't dive into this atm, you can try to search examples on their website how to get it done.
If you still having problem with that, you can ask it on their discord channel

**Comment by aryab2003** [comment]
Hey, @origranot,I am interested to make this work. Can I go  work on this issue?

**Comment by origranot** [comment]
> Hey, @origranot,I am interested to make this work. Can I go work on this issue?

Go for it champ!

**Comment by aryab2003** [comment]
@origranot Could you please help me with the location of the files that are needed to be changed?

**Comment by origranot** [comment]
Hey @aryab2003 

This files should be located under the verify route.
Did you set up the project locally?

**Comment by UrielOfir** [comment]
@aryab2003 
@mahi25soni 
Are you still working on it?

**Comment by UrielOfir** [comment]
Can someone check if this issue is still relevant?

**Comment by UrielOfir** [comment]
@essofyany
It's great to hear that you are still woriking on it :)
Keep with your good work!

**Comment by origranot** [comment]
@essofyany Well done!
