### ISSUE TITLE
App link is not working

### ISSUE THREAD

**Issue by Tamir198** [origranot/reduced.to#415]
### Description

In the top part of the README the app link is not working:

### Screenshots

![image](https://github.com/origranot/reduced.to/assets/34707669/c21d885c-103a-4dc9-8fd6-40bdbe0e9f89)
![image](https://github.com/origranot/reduced.to/assets/34707669/87fe1c9b-65cd-49e4-a494-05f41ac4eff6)

**Comment by maha885** [comment]
Hi, I was trying to open that , it redirected to the official website. Working fine in the device

**Comment by Tamir198** [comment]
Thats weird, I wonder if the problem is on my computer maybe? We should check this with more people and see if they can get the same error as well

**Comment by origranot** [comment]
> Thats weird, I wonder if the problem is on my computer maybe? We should check this with more people and see if they can get the same error as well

That's a good idea, I will leave the issue open to see if more people come across this problem.

**Comment by ronnahmias** [comment]
Hello, I have tried the link now and it works fine.
