### ISSUE TITLE
Create statistics components for the admin panel

### ISSUE THREAD

**Issue by origranot** [origranot/reduced.to#423]
### Description

- Create a card for registered users count.
- Create a card for new urls count (only from database)
- Create a card for urls being stored in the cache (not registered users)

NOTE: Consider adding the monthly change.
Make sure to use Stat component from Daisyui.

### Additional information

ref: https://daisyui.com/components/stat/

**Comment by Haim-S** [comment]
Hello, I take the assignment

**Comment by origranot** [comment]
> Hello, I take the assignment

Great!

**Comment by origranot** [comment]
@Haim-S Hey, are you still working on it?

**Comment by Sakshi-75** [comment]
Hi @origranot , can I work on this?

**Comment by origranot** [comment]
> Hi @origranot , can I work on this?

Sure, go for it!

**Comment by Sakshi-75** [comment]
Hi @origranot ,
I've added the stats with the first two values. I've created backend endpoint as well to fetch those stats. But I'm not sure where to get the third value from. Can you help me out with that?
![image](https://github.com/origranot/reduced.to/assets/20265098/739767b0-ccf1-4e2f-b480-1a3ff6e0e632)
(Currently the value in the third field is hardcoded dummy value)

**Comment by Anjali-Git-Hub** [comment]
i want to handle this issue please assign it to me .

**Comment by origranot** [comment]
@Sakshi-75 We can fetch this values from the Cache service.
Let's start with the number of Registered users and etc.

**Comment by Sakshi-75** [comment]
Hi @origranot , are these values already being saved in the cache? Because I couldn't see them in the cache storage on inspecting.

**Comment by origranot** [comment]
> Hi @origranot , are these values already being saved in the cache? Because I couldn't see them in the cache storage on inspecting.

As I said the urls count and etc can be fetched from the cache.
I think we should start with the number of registered users.

I think it should be done in cards. more gap between the stats.

**Comment by origranot** [comment]
Fixed in https://github.com/origranot/reduced.to/pull/581
