### ISSUE TITLE
Request for AVG to release block

### ISSUE THREAD

**Issue by yaelih** [origranot/reduced.to#430]
### What would you like to share?

AVG blocks [reduced.to](https://reduced.to/) and reports "URL:Blacklist".
Make a request to AVG to release this block.

**Comment by yaelih** [comment]
Please assign it to me.
I reported it and will update when I get a response.

**Comment by origranot** [comment]
> Please assign it to me. I reported it and will update when I get a response.

 I just did, good job 🚀

**Comment by yaelih** [comment]
They cleared the block :) It works now.
We can close this issue.

**Comment by origranot** [comment]
> They cleared the block :) It works now. We can close this issue.

That's amazing, good job! 🚀
