### ISSUE TITLE
Implement User Limit for Active URLs 

### ISSUE THREAD

**Issue by shlomots** [origranot/reduced.to#437]
### Description

**Limiting Active URLs per User:** To prevent potential misuse and ensure fair distribution of resources, we might consider imposing a cap on the number of active URLs a user can generate and maintain simultaneously.

**Comment by origranot** [comment]
Great idea!

I will assign you to it 💯

**Comment by MayurShirodkarOfficial** [comment]
If this issue is still open can i try working on this ?

**Comment by UrielOfir** [comment]
@shlomots
Are you still working on it?

**Comment by UrielOfir** [comment]
Can someone check if this issue is still relevant?

**Comment by essofyany** [comment]
Hi everyone,
I'm open to work on this, I just need more explanation about this feature

**Comment by UrielOfir** [comment]
@origranot Can you help @essofyany with it?

**Comment by origranot** [comment]
> Hi everyone, I'm open to work on this, I just need more explanation about this feature

We would like to limit users to create only up to X number of links.
But I think this issue is blocked by: https://github.com/origranot/reduced.to/issues/640.

**Comment by tomersf** [comment]
Hey @origranot , I can take the issue.
is there a certain limit on which we want to impose?

**Comment by origranot** [comment]
> Hey @origranot , I can take the issue.
> 
> is there a certain limit on which we want to impose?

Awesome!

We can start with 10 active links at all time.

Also it would be great if we can show the limits in the settings page.
