### ISSUE TITLE
Add URL Management Dashboard

### ISSUE THREAD

**Issue by shlomots** [origranot/reduced.to#438]
### Description

**User Dashboard for URL Management:** A dedicated dashboard for users could enhance the user experience. This dashboard would:

- Display all the URLs a particular user has generated.
- Clearly show how many more URLs they're allowed to create under their limit.
- (Potential feature) Provide some basic analytics on their URLs, such as the number of clicks

**Comment by origranot** [comment]
That's a great idea!

I will assign you to this issue :)

**Comment by andresousadotpt** [comment]
Hello! Is this issue still up for development? 
If yes I might be able to contribute :)

**Comment by MenotiFilho** [comment]
Hey, i found your project searching on the #contributions-welcome tag and i think i can implement this one, can you assign this one to me?

**Comment by shlomots** [comment]
I'm on it, finishing it up, thank you

**Comment by MenotiFilho** [comment]
my bad

**Comment by origranot** [comment]
@MenotiFilho There are many more features to implement!

**Comment by origranot** [comment]
Fixed in https://github.com/origranot/reduced.to/pull/581
