### ISSUE TITLE
Move the logger to an internal lib

### ISSUE THREAD

**Issue by origranot** [origranot/reduced.to#445]
### Description

Right now we are using a custom logger module within our backend app.

In the near future we are planning to create more micro-services to use this code.
We need to create an internal library and expose a logger module from it. (similar to the config lib)
```
.
├── apps/
│   ├── backend/
│   │   └── main.ts
│   └── frontend
└── libs/
    ├── logger
    ├── config
    └── prisma
```

### Additional information

https://nx.dev/packages/node/generators/library

**Comment by senderh55** [comment]
I will take it

**Comment by origranot** [comment]
> 
> 
> I will take it
> 
> 
> 
> 

@senderh55 Awesome 🤩

**Comment by origranot** [comment]
https://github.com/origranot/reduced.to/pull/449
