### ISSUE TITLE
Verification email gives me a wrong url

### ISSUE THREAD

**Issue by MenotiFilho** [origranot/reduced.to#447]
### Description

The link the user receive on the verification email sends the user to a a url like this "https://localhost/register/verify/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoienptbnQiLCJlbWFpbCI6Im1lbm90aW1maWxob0BnbWFpbC5jb20iLCJpYXQiOjE2OTUwNjQ4NzgsImV4cCI6MTY5NTE1MTI3OH0.MDnUbgid0m5SdrS2OBXo8dKdjyS1SqWQgF-u3VhtnWk" which won`t work since its a localhost

**Comment by origranot** [comment]
Nice, catch. working on a fix :)

**Comment by origranot** [comment]
@MenotiFilho Fixed, please register again 👑
