### ISSUE TITLE
[DOCS] Add an intro gif for the usage examples

### ISSUE THREAD

**Issue by origranot** [origranot/reduced.to#451]
### Description

We should add an updated GIF that explain about the usage of the website.
Simply record the screen when shortening a new url.

### Additional information

You can put the gif within a new folder called assets / images at the root of the repo.

**Comment by noobpro07** [comment]
I have submitted the pull request you can check it

**Comment by noobpro07** [comment]
@origranot can you please check the pull request

**Comment by saku1331** [comment]
I wish to work on this issue. Kindly assign me this.

**Comment by origranot** [comment]
> I wish to work on this issue. Kindly assign me this.

@saku1331 Thank you so much!
This issue already been addressed.

**Comment by origranot** [comment]
https://github.com/origranot/reduced.to/pull/459

**Comment by saku1331** [comment]
> > I wish to work on this issue. Kindly assign me this.
> 
> @saku1331 Thank you so much! This issue already been addressed.

okay your welcome
