### ISSUE TITLE
[SEO Improvements] - Register page

### ISSUE THREAD

**Issue by origranot** [origranot/reduced.to#456]
### Description

Set up title and metadata inside the head tag.
You can take a look how it implemented inside the main page:
https://github.com/origranot/reduced.to/blob/master/apps/frontend/src/routes/index.tsx#L182

<img width="321" alt="image" src="https://github.com/origranot/reduced.to/assets/48911144/c502bc8f-7243-4a89-806c-fe71943646cf">

**Comment by tbetous** [comment]
Hello @origranot !

I would like to make it for the hacktoberfest event. Can you assign me on this ?

**Comment by tbetous** [comment]
To be counted for the hacktoberfest, this PR need to be pushed between 1st October and the 31 October. Weird rule. I'll reopen the PR the 1st October. 🤦

    Your PR/MRs must be created between October 1 and October 31 (in any time zone, UTC-12 thru UTC+14).
    Your PR/MRs must be made to a public, unarchived repository.

**Comment by SyedaMahamFahim** [comment]
Hello, I am interested in working on this task for the upcoming Hacktoberfest.

**Comment by origranot** [comment]
Sounds good!

**Comment by jharahul-28** [comment]
I want to work on the issue. Please assign this issue to me.

**Comment by origranot** [comment]
> I want to work on the issue. Please assign this issue to me.

Hey!

Thank you for your help, this issue is already assigned and hopefully will be resolved soon.

There are another issues to help with 👑

**Comment by AbdishakourY** [comment]
Assign me one task please!

**Comment by Kyl67899** [comment]
I am willing to contribute to this assignment.
