### ISSUE TITLE
[DOCS] npm run install:all does not work

### ISSUE THREAD

**Issue by tbetous** [origranot/reduced.to#458]
### Description

Step 2 to of the [installation documentation](https://github.com/origranot/reduced.to#-installation) is 

```
npm install && npm run install:all
```

However I don't have any script for `install:all`.  It's probably a mistake. What do you think?

It should be just `npm install`

Screenshot of the execution on my local.

### Screenshots

<img width="374" alt="image" src="https://github.com/origranot/reduced.to/assets/4435536/825802f4-3fd5-40f2-8f5f-51308ab8b2c6">

**Comment by origranot** [comment]
That's a good catch, we don't need the install:all script.
You are more than welcome to open a PR to fix it 👍

**Comment by MOHIT-PANDEY215** [comment]
Hey! Could you please assign this issue to me? I would like to implement this fix.

**Comment by origranot** [comment]
> Hey @origranot ! Could you please assign this issue to me? I would like to implement this fix.

Go for it champ 👑

**Comment by origranot** [comment]
Done https://github.com/origranot/reduced.to/pull/474
