### ISSUE TITLE
Change X (formerly Twitter) logo to their new logo

### ISSUE THREAD

**Issue by origranot** [origranot/reduced.to#460]
### Description

We need to change the old logo of X (formerly Twitter) to their new logo.
![image](https://github.com/origranot/reduced.to/assets/48911144/1f7175ea-d2e9-40fe-b5a5-fe1466c5a221)

### Additional information

Make sure to add it to the dark and light theme.

**Comment by SoNiC-HeRE** [comment]
i can fix this, assign me this pls

**Comment by origranot** [comment]
> i can fix this, assign me this pls

Go for it Champ👑

**Comment by origranot** [comment]
Done in https://github.com/origranot/reduced.to/pull/468
