### ISSUE TITLE
[BUG]: link not working

### ISSUE THREAD

**Issue by barkhaaroraa** [origranot/reduced.to#465]
### Description

At the end of the overview (documentation) page there's a "edit this page" link, on clicking the link a 404 error page pops up. 

### Screenshots

<img width="1106" alt="image" src="https://github.com/origranot/reduced.to/assets/115429121/a22b008d-52a1-4056-a7bf-6f6578fca561">
<img width="1109" alt="image" src="https://github.com/origranot/reduced.to/assets/115429121/94b90d1e-ec70-45e7-8aef-d632aed00199">

**Comment by origranot** [comment]
Hey @barkhaaroraa,

Nice catch, do you want to address one of the issues you opened?

**Comment by barkhaaroraa** [comment]
yeah sure i'd like to work on all 3 of them, please assign them to me

**Comment by origranot** [comment]
> yeah sure i'd like to work on all 3 of them, please assign them to me
Go for it 🚀 
I assigned you to them.

**Comment by NawinKumarSharma** [comment]
can you please assign me? i want to work on this

**Comment by origranot** [comment]
@Roshanbhadauriya You are welcome to work on it.

**Comment by Roshanbhadauriya** [comment]
Can you provide me some details like ,Where should I have to redirect/transfer the the user after clinking on the link.
