### ISSUE TITLE
[DOCS]: Typo on the overview page

### ISSUE THREAD

**Issue by barkhaaroraa** [origranot/reduced.to#466]
### Description

the spelling of reduced.to is incorrect.

### Screenshots

<img width="972" alt="image" src="https://github.com/origranot/reduced.to/assets/115429121/ebaf118b-f4b6-491d-b802-a80f54782d1b">

**Comment by pAkalpa** [comment]
I want to work on this issue. I will do a pull request in October (For Hacktoberfest).

**Comment by origranot** [comment]
> I want to work on this issue. I will do a pull request in October (For Hacktoberfest).

Hey @pAkalpa,
This issue is already assigned and will be resolved by @barkhaaroraa.
Thank you for your intention, you are more than welcome to contribute to other issues!

**Comment by origranot** [comment]
https://github.com/origranot/reduced.to/pull/471
