### ISSUE TITLE
[BUG]: Logo link not working on the overview page

### ISSUE THREAD

**Issue by barkhaaroraa** [origranot/reduced.to#467]
### Description

the logo link on the overview page isnt working/leading back to the home page.

### Screenshots

<img width="825" alt="image" src="https://github.com/origranot/reduced.to/assets/115429121/d916ceb1-3d94-4d46-8712-a5d048f0c9bd">

**Comment by pAkalpa** [comment]
I want to work on this issue. I will do a pull request in October (For Hacktoberfest).

**Comment by origranot** [comment]
> I want to work on this issue. I will do a pull request in October (For Hacktoberfest).

Hey @pAkalpa,
This issue is already assigned and will be resolved by @barkhaaroraa.
Thank you for your intention, you are more than welcome to contribute to other issues!

**Comment by SrijitaBaksi** [comment]
Hey , since the logo issue isn't resolved yet can i work on it? If you can please assign this task to me under Hacktober fest 2023!

**Comment by barkhaaroraa** [comment]
hi, i'm facing some problems while running it locally, do you have a discord server wherein i could address my problems?

**Comment by Sha1kh4** [comment]
If I'm not mistaken, you mean that the logo should send users to reduced.to rather than docs? If so, I believe I can resolve this issue so please assign me this issue

**Comment by origranot** [comment]
> hi, i'm facing some problems while running it locally, do you have a discord server wherein i could address my problems?

Hey, what are the issues?

**Comment by barkhaaroraa** [comment]
<img width="663" alt="image" src="https://github.com/origranot/reduced.to/assets/115429121/eab3b3a9-8966-43f9-99c7-cde6dfbc8794">
so i was trying to run the repo locally by following the installation guidelines but i'm getting this error on "npx nx serve backend" command. tried running it via admin too, still the same problem... not sure what i'm doing wrong.

**Comment by origranot** [comment]
> <img alt="image" width="663" src="https://user-images.githubusercontent.com/115429121/271967460-eab3b3a9-8966-43f9-99c7-cde6dfbc8794.png"> so i was trying to run the repo locally by following the installation guidelines but i'm getting this error on "npx nx serve backend" command. tried running it via admin too, still the same problem... not sure what i'm doing wrong.

Hey, after searching it online it looks like it's a common problem.
Can you try this solution? https://github.com/prisma/prisma/issues/9184#issuecomment-917396506

Migrate and generate won't work like that, you have to run (in the root folder):
`nx generate-types prisma`
`nx migrate-dev prisma --name=init`

**Comment by Sha1kh4** [comment]
@origranot can I work on this issue?

**Comment by origranot** [comment]
@Sha1kh4 Hey!

I can see that @barkhaaroraa is already assigned to this issue.
You are more than welcome to contribute to a free issue 💯

**Comment by mahi25soni** [comment]
@origranot if barkha haven't done that, or have forgotten, do consider me as assignee

**Comment by origranot** [comment]
> @origranot if barkha haven't done that, or have forgotten, do consider me as assignee
Let's give him a few more days.
@barkhaaroraa Are you still on it?

**Comment by barkhaaroraa** [comment]
hi, i'm currently swamped with exams until October 12th, so I won't be able to tackle the issue right away. Although, I've hit a roadblock with the issue, but I'm determined to give it another shot after my exams. Can you please give me until October 15th? If it's not possible, let me know.

**Comment by barkhaaroraa** [comment]
hi, ive fixed the issue please review @origranot
