### ISSUE TITLE
Transparent Navbar in Overview Page

### ISSUE THREAD

**Issue by raviikushh** [origranot/reduced.to#473]
### Description

While scrolling in overview page the left sidebar is not looking good as it is going behind the Navbar and it is completely visible.
Navbar is also not visible in dark mode.

### Screenshots

![Screenshot (213)](https://github.com/origranot/reduced.to/assets/77044005/31a602ec-e17b-4643-94ee-64665e17cad5)
![Screenshot (214)](https://github.com/origranot/reduced.to/assets/77044005/b89341fa-1374-4a22-b4f2-95d1989a47a8)
![Screenshot (216)](https://github.com/origranot/reduced.to/assets/77044005/088dbc8f-7a02-4bbb-8b23-414193a5fa04)

### Additional information

Please assign me I'll fix this bug.

**Comment by origranot** [comment]
Nice catch!

Do you want to work on this issue?

**Comment by raviikushh** [comment]
> @raviikushh Nice catch!
> 
> Do you want to work on this issue?

Yeahh sure

**Comment by origranot** [comment]
> > @raviikushh Nice catch!
> > Do you want to work on this issue?
> 
> Yeahh sure I'll fix all of them.

Go for it 👑

**Comment by raviikushh** [comment]
I'm unable to setup docker due to low pc specs, I would like to request you to assign the issue to someone else.

**Comment by SoNiC-HeRE** [comment]
I can get this fixed, assign me pls

**Comment by Debangan202Ok** [comment]
caught up! @origranot 
Should i pull?

**Comment by origranot** [comment]
@Debangan202Ok Sounds good!
Go for it 👑

**Comment by Debangan202Ok** [comment]
> @Debangan202Ok Sounds good!
> Go for it 👑 

Thanks! @origranot 
Working ok it.....
Will fix it🤞

**Comment by origranot** [comment]
Done https://github.com/origranot/reduced.to/pull/476
