### ISSUE TITLE
QR code is not cleary visible

### ISSUE THREAD

**Issue by pratyushsingha** [origranot/reduced.to#477]
### Description

The QR code is not clearly visible and the scanner doesn't catch the link from that code...and in the bottom there the background of the qr is also not fully visible

### Screenshots

![image](https://github.com/origranot/reduced.to/assets/111200225/aeaaf48c-e5fe-40e8-a86f-201ca981ecd7)

### Additional information

Please assign me I'll fix this bug.

**Comment by origranot** [comment]
@pratyushsingha Hey!

Maybe I did not understand you, but you can scroll down and see the whole QRcode.

**Comment by pratyushsingha** [comment]
https://github.com/origranot/reduced.to/assets/111200225/69aca2f9-f323-4699-84af-51bdfbf07339

**Comment by pratyushsingha** [comment]
@origranot can  u please checkout the video

**Comment by siddharth9300** [comment]
@origranot the page is not scrollable if the display size is smaller then the QR code is being cut out. you need to zoom out to see the QR code.

**Comment by origranot** [comment]
@pratyushsingha I can see the issue.

You are more than welcome to work on it!

**Comment by pratyushsingha** [comment]
@origranot ok i am trying to solve it

**Comment by origranot** [comment]
@pratyushsingha Hey, any progress?
Did you managed to set it up?

**Comment by mahi25soni** [comment]
Whats the issue? assign me this

**Comment by pratyushsingha** [comment]
@origranot o can't setup the backend actually...i am trying to set it up..

**Comment by siddharth9300** [comment]
@origranot I have found the actual cause of the problem and I am working on it. Please assign me this issue.

**Comment by 0xatulpatil** [comment]
hey @origranot , can I take this up?

**Comment by DevanshKyada27** [comment]
Hey, @origranot can you please assign this issue to me 

I want to work on it....

**Comment by pratyushsingha** [comment]
ahh i am able to set it up finally...but i think the issue is resolved...isn't it?? :)
![Screenshot from 2023-10-08 00-50-35](https://github.com/origranot/reduced.to/assets/111200225/aa123ccd-ca6d-4002-a555-cf71b7eec3e7)

**Comment by origranot** [comment]
> ahh i am able to set it up finally...but i think the issue is resolved...isn't it?? :)
> 
> ![Screenshot from 2023-10-08 00-50-35](https://github.com/origranot/reduced.to/assets/111200225/aa123ccd-ca6d-4002-a555-cf71b7eec3e7)
> 
> 

I wasn't able to replicate it as well. I will close the issue for now.
