### ISSUE TITLE
[BUG]: No right margin in toggle switch in Navbar

### ISSUE THREAD

**Issue by siddharth9300** [origranot/reduced.to#479]
### Description

There is no right margin in the dark mode toggle switch which is looking uneven I would like to work on this issue.

### Screenshots

![image](https://github.com/origranot/reduced.to/assets/83226178/c1d17a2d-97e0-405c-be77-72642b1b94e7)

**Comment by origranot** [comment]
@siddharth9300 That's true, go for it!

**Comment by HridoyHazard** [comment]
@origranot hi can i take this issue ? i already made the change and fixed the bug just waiting for your assign and made pr...

**Comment by siddharth9300** [comment]
The issue has been solved. Please accept pull request.
