### ISSUE TITLE
[BUG]:Font color of logo in navbar is not matched with the logo in hero in Dark Mode

### ISSUE THREAD

**Issue by siddharth9300** [origranot/reduced.to#480]
### Description

Font color of logo in navbar is not matched with the logo in hero in Dark Mode. we must create a logo for dark mode that can be used when dark mode is enabled.

### Screenshots

![image](https://github.com/origranot/reduced.to/assets/83226178/bd4b4a30-307c-4d2f-937a-44c72a955753)

**Comment by siddharth9300** [comment]
I would also like to work this issue.

**Comment by origranot** [comment]
@siddharth9300 go for it champ!

**Comment by Anjali-Git-Hub** [comment]
i want to handle this issue please assign it to me .

**Comment by origranot** [comment]
@Anjali-Git-Hub Hey,

There is already an ongoing PR.
