### ISSUE TITLE
Multiple domain support with subdomain possibility

### ISSUE THREAD

**Issue by thistehneisen** [origranot/reduced.to#492]
### Description

Would be a nice feature if it could have multiple domains, and possibility to short to a subdomain instead of path. e.g. shortened url becomes xyz.domain1.tld or yxz.domain2.tld, if a different domain is selected.

**Comment by origranot** [comment]
That's an option, other domains cost money to maintain.
I pay the "reduced.to" domain, it ain't cheap.

There is another option, someone bring up the idea to maintain list of all the public instances. It can suit your needs as well.
