### ISSUE TITLE
Request to Add Password Criteria Tooltip in Text Area

### ISSUE THREAD

**Issue by vinayakjaas** [origranot/reduced.to#493]
### Description

When users move their cursor over the password input field, a tooltip or a small pop-up message should appear. This message would provide clear and concise information about the password criteria, such as:

Minimum length requirement .
Special character requirement (if applicable).
Uppercase and lowercase letter requirements (if applicable).
Any other relevant criteria.

### Screenshots

![Screenshot 2023-10-06 201941](https://github.com/origranot/reduced.to/assets/96948435/d6b222a3-0ca1-4a5b-9e74-e36124d4877e)

**Comment by origranot** [comment]
We do have explanation under the password field.
I don't think it's that important.
