### ISSUE TITLE
[DOCS] Improve Overview.md

### ISSUE THREAD

**Issue by ayan-joshi** [origranot/reduced.to#495]
### Description

I would like to enhance the content of overview.md file to explain the reduced.io in a more appropriate way .
I will add the example how it works and also add the contact us section as well.

### Additional information

Please assign me this issue under hacktoberfest label @origranot

**Comment by origranot** [comment]
Go for it champ 🤩

There is also a docs website you can contribute to. (https://docs.reduced.to)

**Comment by ayan-joshi** [comment]
> Go for it champ 🤩
> 
> There is also a docs website you can contribute to. (https://docs.reduced.to)

Lesgo thanks
