### ISSUE TITLE
Request to Update Cookie Permission Button Label from 'Okay' to 'Accept

### ISSUE THREAD

**Issue by vatsalya-vyas** [origranot/reduced.to#499]
### Description

Propose changing the cookie permission button label from "Okay" to "Accept" for improved clarity and user-friendliness. 

### Screenshots

![Screenshot 2023-10-08 025935](https://github.com/origranot/reduced.to/assets/140804211/03d4d764-7f38-4ad8-bf8b-228c03aed285)

**Comment by vatsalya-vyas** [comment]
I am interested in resolving this issue

**Comment by origranot** [comment]
Sounds good!

**Comment by prakhar1535** [comment]
i want to work on this issue , pleaese assign

**Comment by JoyelJohny** [comment]
Can i work on this

**Comment by heysagnik** [comment]
I want to work on this issue
