### ISSUE TITLE
Generic High Entropy Secret

### ISSUE THREAD

**Issue by pratyushsingha** [origranot/reduced.to#502]
### What would you like to share?

![Screenshot from 2023-10-08 18-00-30](https://github.com/origranot/reduced.to/assets/111200225/fff965d8-f53c-49ce-8b56-f4d13b25196f)

https://dashboard.gitguardian.com/share/incidents/880e83a1-4e0e-4d88-8705-7f8d4e4793eb
the accesstoken secret is exposed publicly

**Comment by origranot** [comment]
That's a good call. I think I will just remove the accessToken and the remote cache for now.
Do you want to create a PR for that?
@pratyushsingha

**Comment by pratyushsingha** [comment]
@origranot  yess sure :)

**Comment by UrielOfir** [comment]
@pratyushsingha 
Are you still working on it?

**Comment by UrielOfir** [comment]
Can someone check if this issue is still relevant?
