### ISSUE TITLE
Password show/hide button is overlapping with password input

### ISSUE THREAD

**Issue by pratyushsingha** [origranot/reduced.to#503]
### Description

I encountered an issue on the Register page where the password show/hide button is overlapping with the password input field, making it difficult to interact with and potentially causing usability issues for users during registration.

### Screenshots

![Screenshot from 2023-10-08 18-14-09](https://github.com/origranot/reduced.to/assets/111200225/86287e4e-82f4-4398-a063-39b23894c48d)
![image](https://github.com/origranot/reduced.to/assets/111200225/492b40a6-90c9-409d-a99a-7732bbda73c4)

### Additional information

i want to fix the issue...can u please assign it to me...i have set it up on my local environment also

**Comment by pratyushsingha** [comment]
@origranot can u please checkout the issue #505 ...and i have solved the issue and here is the PR #505

**Comment by origranot** [comment]
Done https://github.com/origranot/reduced.to/pull/505
