### ISSUE TITLE
Add report button for fraud and scam reporting

### ISSUE THREAD

**Issue by origranot** [origranot/reduced.to#520]
### Description

We want to implement a report button feature to address concerns related to fraud, scams, and other malicious activities. This will enable users to flag suspicious URLs for further review and allow our administrators to take appropriate actions, such as removing the reported URLs.

**Comment by shivamp1998** [comment]
can i work on this issue?

**Comment by origranot** [comment]
> can i work on this issue?

I thought I am going to implement it, I guess we can split this into backend and frontend tasks.
Where do you think we should place the Report button?

**Comment by shivamp1998** [comment]
I think it would be fine here
![image](https://github.com/origranot/reduced.to/assets/48366063/668115d1-70d2-4419-a071-c168c91ae579)
what are your thoughts?

**Comment by origranot** [comment]
> I think it would be fine here ![image](https://user-images.githubusercontent.com/48366063/275879208-668115d1-70d2-4419-a071-c168c91ae579.png) what are your thoughts?

The button should be visible at all time..
