### ISSUE TITLE
Inconsistency in Global Header Logo

### ISSUE THREAD

**Issue by iamjatinchauhan** [origranot/reduced.to#528]
### Description

Docs
![image](https://github.com/origranot/reduced.to/assets/40722235/22d89951-109c-492c-8b7c-8e677b4334a3)

Privacy Policy
![image](https://github.com/origranot/reduced.to/assets/40722235/95999896-880c-4d4f-872e-d4cdbf1a4246)

Suggestion
* Privacy Policy should be Heading of Webpage.
* Privacy Policy should be opened in new tab.
* At Privacy Policy, Global Header Position to be Sticky instead of relative.

### Screenshots

![image](https://github.com/origranot/reduced.to/assets/40722235/c0a3f31f-bdba-4c4f-af29-830fa60942ea)

In reference to second suggestion

**Comment by origranot** [comment]
This is the navbar, this is not the header.
Can you explain in more depth? maybe you meant we should add the privacy policy to the docs?

**Comment by singodiyashubham87** [comment]
@origranot Actually he want to say that Privacy policy must have to be larger in font size as it is the header(heading) and other section should have to be subsections of it, currently due to almost same font size they all are looking as different headings

![image](https://github.com/origranot/reduced.to/assets/93720428/b823aae1-db0d-4e4f-8aff-12da69eb297d)

I you assign me this issue then I can resolve it.

**Comment by iamjatinchauhan** [comment]
@origranot 
Nav bar is not stable/fixed at Privacy Policy page.
Also, clicking on _Privacy policy_ consent banner, privacy policy webpage should be opened in new page as in screenshot 3 (it is showing privacy policy hyperlink in same privacy policy webpage.

**Comment by singodiyashubham87** [comment]
@iamjatinchauhan I can do but first I need to be assigned the issue.

**Comment by origranot** [comment]
@singodiyashubham87 Go for it.
Maybe you can add some more legal content to the privacy policy...?

**Comment by singodiyashubham87** [comment]
@iamjatinchauhan Hey, If you don't mind can I take up this issue?

**Comment by iamjatinchauhan** [comment]
@singodiyashubham87 Sure, Work on this.

**Comment by singodiyashubham87** [comment]
@origranot He is ready to transfer the issue to me, Kindly assign me this issue, I wanna work on it.

**Comment by UrielOfir** [comment]
@singodiyashubham87 
Is it still relevant for you to work on this issue?

**Comment by singodiyashubham87** [comment]
@UrielOfir Nope! You can take up the issue.

**Comment by UrielOfir** [comment]
Can someone check if issue is still relevant?

**Comment by essofyany** [comment]
Can I work on this?

**Comment by UrielOfir** [comment]
@essofyany Go for it!

**Comment by origranot** [comment]
Done in https://github.com/origranot/reduced.to/issues/528
