### ISSUE TITLE
Display the email to verify

### ISSUE THREAD

**Issue by icepick4** [origranot/reduced.to#532]
### Description

Currently when you create your account and you are verifying your email, (unless I did a mistake) the email is not displayed anywhere.

It might cool to be displayed on one of the following components :

### Screenshots

![image](https://github.com/origranot/reduced.to/assets/82316285/1063d813-527f-4997-a956-9d1047f0c652)

![image](https://github.com/origranot/reduced.to/assets/82316285/d849a370-5bae-4d91-97ca-0f1199eb2c5e)

### Additional information

Pay no attention on the font its my font system.

**Comment by origranot** [comment]
That's a good idea!

Do you want to implement this?

I think it is more than enough to put the mail on the verification page.
What do you think?

**Comment by singodiyashubham87** [comment]
@origranot I would love to work on the issue.
