### ISSUE TITLE
Different background color on selection pseudo state

### ISSUE THREAD

**Issue by singodiyashubham87** [origranot/reduced.to#535]
### Description

The reduced.to logo and the text below it are both have different background colors on selection which is making the UI inconsistent, I want to make the background of the text also same on the selected state

### Screenshots

![image](https://github.com/origranot/reduced.to/assets/93720428/992a1847-1849-4aa6-b2ff-84676fc7f421)
![Screenshot from 2023-10-23 15-23-38](https://github.com/origranot/reduced.to/assets/93720428/521ef813-b7a1-45e3-885d-ff0accc51f32)

**Comment by siddharth9300** [comment]
This is happening due to filter property

**Comment by singodiyashubham87** [comment]
@siddharth9300 Still it will be better if we make this change, It will give a unique look to the website.

**Comment by singodiyashubham87** [comment]
@origranot This is what I want to do.
Previously this color was blue on selection as shown in the issue attached screenshot.
![image](https://github.com/origranot/reduced.to/assets/93720428/5fda6a53-32aa-4f99-aa60-356c4e79bfd1)

**Comment by origranot** [comment]
I am not sure is that valuable, we can skip it for now!
Thank you for your contribution @singodiyashubham87
