### ISSUE TITLE
[DOCS] Make the steps a bulleted list in the "How does it work" section

### ISSUE THREAD

**Issue by singodiyashubham87** [origranot/reduced.to#536]
### Description

We can make the section more appealing and understandable to the user by explaining the steps in bullet points.

### Screenshots

![image](https://github.com/origranot/reduced.to/assets/93720428/2f827231-92d0-4ef8-9de8-67ca6ebd0d05)

### Additional information

Kindly assign me this issue.

**Comment by myselfprincee** [comment]
This will be so quick. it will only require 1-2 minutes.

**Comment by origranot** [comment]
Go for it! @singodiyashubham87

**Comment by singodiyashubham87** [comment]
@origranot I've setup the web app in my local environment but when I click on the docs button it redirects to the original website "docs.reduced.to" and therefore I'm not able to see if my changes are reflected or not, How can I check it?

**Comment by khanjanSanghavi** [comment]
@singodiyashubham87  For that you need to make changes directly from GitHub 
No worries I have fixed it

**Comment by khanjanSanghavi** [comment]
I have one suggestion  @origranot 
we are also providing one feature of extending expiration time for registers user 
I think we should also mention that with the dashboard feature

**Comment by singodiyashubham87** [comment]
@origranot Khanjan added a PR of his own what should I do now?

**Comment by myselfprincee** [comment]
> @origranot Khanjan added a PR of his own what should I do now?

Immaturity at it's peak @khanjanSanghavi . You should helped him. It wasn't a big issue that he couldn't solve.

**Comment by origranot** [comment]
@singodiyashubham87 I didn't merge his PR.
You are the one assigned to this issue, I will wait for your PR.
If you do need help don't hesitate to reach out 🚀

**Comment by myselfprincee** [comment]
> @singodiyashubham87 I didn't merge his PR. You are the one assigned to this issue, I will wait for your PR. If you do need help don't hesitate to reach out 🚀

Great @origranot 👏👏

**Comment by khanjanSanghavi** [comment]
> > @origranot Khanjan added a PR of his own what should I do now?
> 
> Immaturity at it's peak @khanjanSanghavi . You should helped him. It wasn't a big issue that he couldn't solve.

Sorry Closing my PR!!

**Comment by khanjanSanghavi** [comment]
@singodiyashubham87  
Here's a quick guide to solve this

- First go to your fork Then make a new branch
- There Go to this path - apps/docs/docs 
- here you will see an overview.md file 
- change accordingly and make a PR 

Didn't wanted to snatch your opportunity 
I am also new to this so was just eager to contribute  

![Screenshot (85)](https://github.com/origranot/reduced.to/assets/75749613/e2f22ebc-f441-4a6f-af29-bce552fffdbb)

**Comment by myselfprincee** [comment]
Hey, Thanks for apologizing to @singodiyashubham87 . I understand the eagerness as I am myself a beginner :) @khanjanSanghavi

**Comment by singodiyashubham87** [comment]
@khanjanSanghavi It's okay, Mate. Maybe you can pick up any other issue or create one for yourself.

**Comment by UrielOfir** [comment]
@singodiyashubham87
Can we close this issue?
