### ISSUE TITLE
Rectify README mistake

### ISSUE THREAD

**Issue by singodiyashubham87** [origranot/reduced.to#542]
### Description

The LICENSE file is not a text(.txt) file but a markdown(.md) file but in the README it's written LICENSE.txt, I want to change that to "LICENSE.md"

### Screenshots

![image](https://github.com/origranot/reduced.to/assets/93720428/589b6a10-22e7-4fd5-be91-28a3bf8aa1fb)

### Additional information

Kindly assign me this issue

**Comment by origranot** [comment]
You can just create a PR changing it into LICENSE (without the suffix)
