### ISSUE TITLE
[DOCS] Add CONTRIBUTING.md file to the repository

### ISSUE THREAD

**Issue by singodiyashubham87** [origranot/reduced.to#543]
### Description

I want to add the CONTRIBUTING.md file to the repository for contributors.

Kindly assign me this issue @origranot

**Comment by origranot** [comment]
Sounds good, go for it champ!

**Comment by HimanshuMahto** [comment]
hey @origranot can i work on this issue

**Comment by mzsrtgzr2** [comment]
hi @origranot i want this issue

**Comment by origranot** [comment]
> hi @origranot i want this issue

Go for it!

**Comment by UrielOfir** [comment]
Is this issue should be closed?

**Comment by mzsrtgzr2** [comment]
nope, i'm on it

**Comment by UrielOfir** [comment]
@mzsrtgzr2 Can we close this issue?
