### ISSUE TITLE
Websites without http or https are invalid

### ISSUE THREAD

**Issue by origranot** [origranot/reduced.to#55]
Currently it gives an "Invalid URL" error when a url is entered (without http or https)

![image](https://user-images.githubusercontent.com/48911144/194360041-a4b5fb99-9d6a-4dae-b072-b2d52e757d75.png)

So to fix this, in this PR i just added "https://" to the url if it doesn't start with the same.
This will also be checked later on, as usual
image

**Comment by Saavrm26** [comment]
May i work on this bug?

**Comment by Saavrm26** [comment]
![image](https://user-images.githubusercontent.com/96730385/194393404-18175b2a-3b92-4c20-bde7-95a79e07c42b.png)
Protocol check is missing

**Comment by origranot** [comment]
> May i work on this bug?
> 
> 

Go ahead, open a or 🙌🏻

**Comment by Saavrm26** [comment]
Umm the latest commit migrates almost the entire project to ts, deleting api.js in the process. I had changes in that file. What to do?

**Comment by origranot** [comment]
You can pull it from master and migrate those changes.

**Comment by akshat-rawat** [comment]
Is this issue still open? If so may I work on it?

**Comment by kadar77** [comment]
May I work on this issue? I already did fix in my local.

For protocol checking, is it allow http and https only?

**Comment by Saavrm26** [comment]
go ahead i'm not able to solve this issue

**Comment by GuillemPM** [comment]
I will write some examples:
If a prefix is missing then should be prefixed with http:// by default (and redirecting to https:// should be handled by the target website, not our task)

* example.com -> should be prefixed with http://
* http://example.com -> as is
* https://example.com -> as is
* (blank) -> Invalid url
* hxtps://example.com ->invalid url (if you can detect it is https, go for it)
* hxtp://example.com -> invalid url (if you can detect it is http, go for it)
* http:/example.com -> protocol should be fixed
* http:example.com -> protocol should be fixed
* http:// -> invalid url
* https:// -> invalid url
* .com -> invalid url

If you have more ideas, lets talk about them, thank you so much guys ♥🚀

**Comment by Riyadutt** [comment]
would like to work on this issue, assign it to me if no one is working on this.

**Comment by origranot** [comment]
@Riyadutt You got it!

**Comment by kadar77** [comment]
Hello,
I am putting my solution here since it is assigned to others. 

`
const regexBadHttp = new RegExp(
  /^([^hH][tT][tT][pP]|[hH][^tT][tT][pP]|[hH][tT][^tT][pP]|[hH][tT][tT][^pP])/
);
const regexUrlSchema = new RegExp(/^(.+:|\.)/);

const prepend = regexUrlSchema.test(body.originalUrl)
    ? ''
    : body.originalUrl.substring(0, 1) === ':'
    ? 'http'
    : 'http:/';
parsedUrl = new URL(
  (prepend + body.originalUrl).replace(regexBadHttp, 'http')
);
`

it can handle all cases mentioned here https://github.com/origranot/reduced.to/issues/55#issuecomment-1279506578 plus 

- :example.com
- :/example.com
- ://example.com
- /example.com
- //exampe.com

**Comment by origranot** [comment]
> Hello, I am putting my solution here since it is assigned to others.
> 
> ` const regexBadHttp = new RegExp( /^([^hH][tT][tT][pP]|[hH][^tT][tT][pP]|[hH][tT][^tT][pP]|[hH][tT][tT][^pP])/ ); const regexUrlSchema = new RegExp(/^(.+:|.)/);
> 
> const prepend = regexUrlSchema.test(body.originalUrl) ? '' : body.originalUrl.substring(0, 1) === ':' ? 'http' : 'http:/'; parsedUrl = new URL( (prepend + body.originalUrl).replace(regexBadHttp, 'http') ); `
> 
> it can handle all cases mentioned here [#55 (comment)](https://github.com/origranot/reduced.to/issues/55#issuecomment-1279506578) plus
> 
> * :example.com
> * :/example.com
> * ://example.com
> * /example.com
> * //exampe.com

Hey, we really like your solution. 

Do you mind open a PR including this?

😄

**Comment by kadar77** [comment]
> 

Thank you, just created the PR. 

Not familiar with procedures for contributing 🙇‍♂️

**Comment by origranot** [comment]
Done https://github.com/origranot/reduced.to/pull/236
