### ISSUE TITLE
QR CODE : Popup

### ISSUE THREAD

**Issue by Vijaykv5** [origranot/reduced.to#550]
### Description

When we click on Scan Code , it open's a QR Code on down. 
Instead of that, we can add that QR code like a model ], users can scan it easily and close the model

### Screenshots

<img width="1301" alt="Screenshot 2023-10-27 at 3 19 46 PM" src="https://github.com/origranot/reduced.to/assets/94985341/ec2331de-39cb-4a86-9b4c-17fa9e3fd906">

### Additional information

It enhances more User-Experience

**Comment by origranot** [comment]
That's a cool idea, do you want to implement it?

**Comment by Vijaykv5** [comment]
Yes @origranot

**Comment by Vijaykv5** [comment]
<img width="1116" alt="Screenshot 2023-10-27 at 7 54 10 PM" src="https://github.com/origranot/reduced.to/assets/94985341/fc984096-fece-4518-87fc-447ec2dd710c">

I'm also getting some errors while setting up locally using docker(while building images)

Would you help me in that

**Comment by Vijaykv5** [comment]
@origranot May you assign me the issue and help me out in above issue

**Comment by origranot** [comment]
@Vijaykv5 I assigned you to the issue.
Regarding the issues you are facing, you are welcome to send me a mail with your discord and I will add you.

**Comment by origranot** [comment]
Fixed in https://github.com/origranot/reduced.to/pull/581
