### ISSUE TITLE
Contacting for Code of Conduct Issues links back to Github repo page 

### ISSUE THREAD

**Issue by iamanurag101** [origranot/reduced.to#552]
### Description

To report instances of abusive, harassing, or otherwise unacceptable behavior may be reported to the community leaders responsible for enforcement, the link provided just redirects to github repo of reduced.to instead of any way of reporting.

### Screenshots

<img width="680" alt="reduced to" src="https://github.com/origranot/reduced.to/assets/139618603/0e213ff1-c7d7-4ce3-bc96-4632cf2b749f">

### Additional information

Would like to work on this issue and provide an alternate link like official e-mail id if maintainers allow me to

**Comment by origranot** [comment]
@iamanurag101 Hey!

Thank you for your contribution.
I know this is the case, at the moment I don't have an official mail for this project.
