### ISSUE TITLE
Grammatical error in the code of conduct

### ISSUE THREAD

**Issue by HimanshuMahto** [origranot/reduced.to#555]
### What would you like to share?

"Community Impact: A violation through a single incident or series of actions."

To make this sentence grammatically correct, you can revise it as follows:

"Community Impact: Occurs through a single incident or a series of actions."
![Screenshot from 2023-10-28 17-20-28](https://github.com/origranot/reduced.to/assets/93067059/cc07cb1e-da10-4b6a-a02d-ebd273e2a942)

**Comment by HimanshuMahto** [comment]
@origranot can I correct it if you say.

**Comment by HimanshuMahto** [comment]
@izdotnet @aigdonia @kadar77 @tbetous @origranot please review the PR generate for this issue #556

**Comment by HimanshuMahto** [comment]
@origranot please review this PR

**Comment by origranot** [comment]
Please stop the spammy issues, this is counterproductive.

**Comment by HimanshuMahto** [comment]
Okk sorry I thought it can help you
