### ISSUE TITLE
Add Facebook Sharing Button for Enhanced Social Sharing

### ISSUE THREAD

**Issue by I-VipulPandey** [origranot/reduced.to#558]
### Description

I propose the addition of a Facebook sharing button to the "reduced.to" website to enhance the user experience and increase social sharing capabilities.

**Comment by I-VipulPandey** [comment]
please assign this issue to me

**Comment by origranot** [comment]
Hey, that's a good idea.
I think that adding Facebook / other social networks will make the ui a bit complex.
We will pass it for now.
