### ISSUE TITLE
Add horizontal scroll functionality to the table component

### ISSUE THREAD

**Issue by origranot** [origranot/reduced.to#559]
### Description

I've noticed an issue with the table in our application where it is not scrollable, and this is causing text overflow. 
When the content within the table exceeds the available width, it becomes difficult to view and interact with the data.

I expect the table to be scrollable horizontally when the content is wider than the container, allowing users to view the complete data without text overflow.

You can view an example of a table with horizontal scroll functionality at this link: [Horizontal Scroll Table Example](https://datatables.net/examples/basic_init/scroll_x.html).

### Screenshots

<img width="365" alt="image" src="https://github.com/origranot/reduced.to/assets/48911144/2d3fd6df-3034-4c47-84ee-f996707d631e">

**Comment by Shubh8899** [comment]
I would like to work on this

**Comment by origranot** [comment]
@Shubh8899 I assigned you, good luck champ 👑

**Comment by saikiran76** [comment]
I would like to work on this. Please assign it

**Comment by origranot** [comment]
> I would like to work on this. Please assign it

Hey!

@Shubh8899 how it's going with this issue? I can see you asked to be assigned.

**Comment by Shubh8899** [comment]
@origranot i am working on it, will finish in couple of days

**Comment by origranot** [comment]
@saikiran76 Hey!
Do you still want to work on this issue?

**Comment by saikiran76** [comment]
Yeah sure.

**Comment by origranot** [comment]
Hey @saikiran76,

had any progress on this issue?
