### ISSUE TITLE
[DOCS]: adding license link on readme

### ISSUE THREAD

**Issue by barkhaaroraa** [origranot/reduced.to#564]
### Description

right now the license hasnt been linked on the readme file, to go to the license i'd have to scroll all the way up or look for the file. so to make the job easier id like to link the license file in the readme section

### Screenshots

<img width="478" alt="image" src="https://github.com/origranot/reduced.to/assets/115429121/05b65377-0b8f-4f5c-95f7-45f2633e8181">

**Comment by barkhaaroraa** [comment]
Hi @origranot could you please review this pr

**Comment by origranot** [comment]
Closed by https://github.com/origranot/reduced.to/pull/565
