### ISSUE TITLE
Registering an account yields an unspecified error.

### ISSUE THREAD

**Issue by Jas-SinghFSU** [origranot/reduced.to#585]
### Description

Running on a local instance but when I register an account, it shows a red line below the input forms but doesn't specify which error I actually got. When I inspect the network tab, it states `400 Bad Request`  with the following error:
```json
{
    "_entry": "9",
    "_objs": [
        true,
        "I",
        {
            "failed": "0",
            "message": "1"
        },
        "\u0001",
        null,
        {
            "0ZgmRGBFUbg": "2",
            "VSZrlYCyHEM": "3",
            "pSTSRe7JjPg": "4"
        },
        "0ZgmRGBFUbg",
        400,
        "/register/",
        {
            "loaders": "5",
            "action": "6",
            "status": "7",
            "href": "8",
            "redirect": "3"
        }
    ]
}
```

The data is actually saved in my database but when I try to log in, it redirects me back to the main page but nothing changes. I'm never actually logged in... what could be causing this? I'm using the Docker container deployment.

### Screenshots

https://github.com/origranot/reduced.to/assets/21210205/0c35b65e-b62b-45d2-bf8b-527d9ae2991e

### Additional information

```bash
[Nest] 1  - 11/24/2023, 10:58:09 AM   ERROR [ExceptionsHandler] Request failed with status code 401
AxiosError: Request failed with status code 401
    at settle (/app/node_modules/axios/dist/node/axios.cjs:1913:12)
    at IncomingMessage.handleStreamEnd (/app/node_modules/axios/dist/node/axios.cjs:3008:11)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Comment by Jas-SinghFSU** [comment]
Additionally, is there any documentation on how to get a custom sub-domain working? I've configured the following params and yet my links only generate as `localhost/kurm0` instead of `links.mydomain.com/a6fd1`. Additionally, none of the links work it seems.
```yml
# General
BACKEND_APP_PORT=3000
FRONTEND_APP_PORT=5000
NODE_ENV=production

# RATE LIMIT
RATE_LIMIT_TTL=60
RATE_LIMIT_COUNT=100

# LOGGER
LOGGER_CONSOLE_THRESHOLD=INFO # DEBUG, INFO, WARN, ERROR, FATAL

# FRONTEND
DOMAIN=links.mydomain.com
CLIENTSIDE_API_DOMAIN=http://links.mydomain.com # Use this verible, while making client side API calls
API_DOMAIN=http://backend:3000 # If you are running with docker compose change this to http://backend:3000

# DATABASE
# If you are running with docker compose change host to postgres
DATABASE_URL="my_db_url"

# REDIS
REDIS_ENABLE=false
REDIS_HOST=localhost
REDIS_PORT=6379
REDIS_PASSWORD=password
REDIS_TTL=1800000  # 30 minutes in milliseconds (default ttl)

# AUTH
JWT_ACCESS_SECRET=my_jwt_secret
JWT_REFRESH_SECRET=my_jwt_secret

# NOVU - You don't need this when running locally (just verify your email from the database)
NOVU_API_KEY=Get it from https://novu.co/


# Memphis (Event streaming service)
MEMPHIS_ENABLE=false # Set this to true if you want to use the event streaming service
MEMPHIS_HOST=Get it from https://memphis.dev/
MEMPHIS_USERNAME=Get it from https://memphis.dev/
MEMPHIS_PASSWORD=Get it from https://memphis.dev/
MEMPHIS_ACCOUNT_ID=Get it from https://memphis.dev/
```

**Comment by origranot** [comment]
Hey @Jas-SinghFSU,

The first problem is probably related to the .env configuration. I would love to see more information about it.
For the second problem with the shortened links, make sure you build the frontend image with the correct values.
<img width="653" alt="image" src="https://github.com/origranot/reduced.to/assets/48911144/16d11b42-99c6-43af-acae-7e3dc49ddbff">

I would love to assist you further via Discord 💯

**Comment by Jas-SinghFSU** [comment]
Thank you for getting back to me @origranot. May I have the discord for the project please? I don't happen to see it in the readme or docs.

**Comment by origranot** [comment]
> Thank you for getting back to me @origranot. May I have the discord for the project please? I don't happen to see it in the readme or docs.

You can send me an email and I will reply with my Discord 💯

**Comment by origranot** [comment]
@Jas-SinghFSU I can verify it now works.
I made some changes. make sure you pull from master and rebuild before running the compose. 🚀
