### ISSUE TITLE
Improve Frontend Dockerfile

### ISSUE THREAD

**Issue by origranot** [origranot/reduced.to#609]
### What would you like to share?

We should improve and rewrite frontend dockerfile to make the image smaller.

### Additional information

You can take inspiration from tracker service.

**Comment by UrielOfir** [comment]
Can you assign me?

**Comment by origranot** [comment]
> Can you assign me?

Go for it champ!

**Comment by origranot** [comment]
Done https://github.com/origranot/reduced.to/pull/616
