### ISSUE TITLE
[BUG] Page width changed when link is too long

### ISSUE THREAD

**Issue by amsali22** [origranot/reduced.to#615]
### Description

if you type a very long link the page takes to length of the link so you have to scroll to the end of the link to find the create new link  button 

i hope you understand me.

### Screenshots

![image_2023-12-17_193755704](https://github.com/origranot/reduced.to/assets/120795779/ac0dad5d-200e-4fd1-9569-6fd4e3f941c9)

**Comment by origranot** [comment]
@amsali22 That's a great catch!
Do you want to work on a fix for that issue?

**Comment by essofyany** [comment]
Hi there
I can work on this bug if no one works on it

**Comment by origranot** [comment]
> Hi there I can work on this bug if no one works on it

Sounds good, go for it!

**Comment by origranot** [comment]
Done https://github.com/origranot/reduced.to/pull/624
