### ISSUE TITLE
Add a stats section in the dashboard section + an option to minimize the sidebar

### ISSUE THREAD

**Issue by Senior-ai** [origranot/reduced.to#625]
### Description

Thereshould be a some kind of a burger icon to minimize the side menu in the dashboard page as it hides most of the table. In addition, there should be a statistics column that redirects to reduced.to/stats/[...urlid]

**Comment by origranot** [comment]
@Senior-ai Sounds amazing, go for it!

**Comment by Senior-ai** [comment]
@origranot yeah no worries, I can start with adding a column

**Comment by origranot** [comment]
@Senior-ai This issue seems to big for me.
I think we should split it into frontend and backend.
There is someone handling the backend part: https://github.com/origranot/reduced.to/issues/652
Also, please open a new issue for the minimize sidebar option

**Comment by Senior-ai** [comment]
> @Senior-ai This issue seems to big for me.
> I think we should split it into frontend and backend.
> There is someone handling the backend part: https://github.com/origranot/reduced.to/issues/652
> Also, please open a new issue for the minimize sidebar option
> 

Already made the stats column working properly. I'll just add the hamburger icon. I'll need assistance with the second issue that I'm working on though, backend wise

**Comment by origranot** [comment]
> > @Senior-ai This issue seems to big for me.
> > I think we should split it into frontend and backend.
> > There is someone handling the backend part: #652
> > Also, please open a new issue for the minimize sidebar option
> 
> Already made the stats column working properly. I'll just add the hamburger icon. I'll need assistance with the second issue that I'm working on though, backend wise

As I said there is another issue #652 that handles the backend side.

**Comment by Senior-ai** [comment]
> > > @Senior-ai This issue seems to big for me.
> > > I think we should split it into frontend and backend.
> > > There is someone handling the backend part: #652
> > > Also, please open a new issue for the minimize sidebar option
> > 
> > Already made the stats column working properly. I'll just add the hamburger icon. I'll need assistance with the second issue that I'm working on though, backend wise
> 
> As I said there is another issue #652 that handles the backend side.
> 

Oh I see I got confused because of the issue you commented on. No worries I'll be in contact w the guy of 652
