### ISSUE TITLE
Link placeholder component is not clear

### ISSUE THREAD

**Issue by 8hachar** [origranot/reduced.to#628]
### Description

the 3 links limit is not clear with the current ui so:
1. design a figma of the url generation and storage component and post it here for cloning
2. design a figma of the solution
3. approve it with @origranot 
4. implement

**Comment by origranot** [comment]
Go for it champ 🏅

**Comment by 8hachar** [comment]
https://www.figma.com/team_invite/redeem/ud0cB5kt09Uy5O7XP3Cxag

**Comment by 8hachar** [comment]
@origranot העיצוב מוכן, מחכה לך בקישור
אם יש כל שינוי שאתה רוצה, תרשום ואני אדאג לו

**Comment by 8hachar** [comment]
https://www.figma.com/file/8X8rCqnFSapkvWvgGJiU3Y/Untitled?type=design&node-id=0-1&mode=design
העיצוב, אני מנסה לעצב משהו אחר בעמוד האחר

**Comment by 8hachar** [comment]
היי כולם, כבר עבר חודש ולא כל כך התקדמתי, יש לי הרבה עבודה, אז אני מבטל את ה-assign שלי, מוזמנים לקחת את ה-issue
