### ISSUE TITLE
[DOCS] adding figma of the page

### ISSUE THREAD

**Issue by 8hachar** [origranot/reduced.to#629]
### Description

there is need for figma of the project to be based on for future design

**Comment by 8hachar** [comment]
link to figma team: https://www.figma.com/team_invite/redeem/ud0cB5kt09Uy5O7XP3Cxag

**Comment by origranot** [comment]
Hey @8hachar,
I don't think it's relevant to the docs, we can share this link and discuss designs in the discord privately.
