### ISSUE TITLE
in "link reporting -> other" add a textbox to allow specifying the reason

### ISSUE THREAD

**Issue by 8hachar** [origranot/reduced.to#630]
### Description

in "link reporting -> other" add a textbox to allow specifying the reason

### Screenshots

![image](https://github.com/origranot/reduced.to/assets/62142226/3b02d452-439d-4cd7-8bc0-77763316a515)
![image](https://github.com/origranot/reduced.to/assets/62142226/f053cda6-5765-4f98-b808-d25d73b79a11)

**Comment by origranot** [comment]
Hey @8hachar,
I believe most of the cases are listed in the dropdown.
It's certainly not a bug.
