### ISSUE TITLE
Implement server side for analytics page

### ISSUE THREAD

**Issue by zivamsa** [origranot/reduced.to#652]
### Description

Implement server side for analytics page

**Comment by UrielOfir** [comment]
@zivamsa 
Do you want to be assigned for that issue?

**Comment by zivamsa** [comment]
Yes

**Comment by UrielOfir** [comment]
You should write your plan before you start, 
And let @origranot give you green light for your plan.

**Comment by origranot** [comment]
Thanks @UrielOfir.

@zivamsa Great idea, go for it!
