### ISSUE TITLE
documentation gif not existing

### ISSUE THREAD

**Issue by 8hachar** [origranot/reduced.to#660]
### Description

the documentation in README.md contains a reference to a gif that does not exist.
 

### Screenshots

![image](https://github.com/origranot/reduced.to/assets/62142226/77e05c69-dc45-4e46-a68f-7e5e42a5fd94)
![image](https://github.com/origranot/reduced.to/assets/62142226/2cf3643c-2310-4f7d-994f-a38ddb277c56)

**Comment by origranot** [comment]
Nice catch, do you want to create a PR for this?

**Comment by 8hachar** [comment]
Give it to someone starting out, it will be good for them

**Comment by Riteshpaul3** [comment]
can you tell me what to do on this issue?
