### ISSUE TITLE
sign up not working on local running

### ISSUE THREAD

**Issue by 8hachar** [origranot/reduced.to#661]
### Description

sign up only shows on right click->open in new window

when trying to enter normally, error is being displayed and nothing happens
but using the right click results in no error 

### Screenshots

![image](https://github.com/origranot/reduced.to/assets/62142226/9f8a7340-5f8e-4b5b-a2bd-592d5b250b09)
![image](https://github.com/origranot/reduced.to/assets/62142226/5036a589-5a11-4b37-8d7f-53fb493eb4d0)

**Comment by origranot** [comment]
Hey @8hachar,

Can you give more information about the problem?
It will be great if you could provide additional information about your setup, configuration etc.

**Comment by 8hachar** [comment]
Default configuration, copied the env on windows and run it, might be a good idea to check with others if they encounter the same thing

**Comment by origranot** [comment]
> Default configuration, copied the env on windows and run it, might be a good idea to check with others if they encounter the same thing

What do you mean by "signup only shows on right click"?
Can you please elaborate on this? maybe attach a video / photos?

**Comment by Senior-ai** [comment]
Try to run it locally on incognito or in a different browser

**Comment by giladfuchs** [comment]
do you run local docker with database?
