### ISSUE TITLE
Link logo has a size issue on dashboard page

### ISSUE THREAD

**Issue by essofyany** [origranot/reduced.to#689]
### Description

On the dashboard page, 
1. On the desktop version, the logo of links in the table has a size issue.
2. On the mobile version, the logo gets replaced with a yellow point

### Screenshots

Desctop version: 
![Capture d’écran du 2024-01-30 16-29-03](https://github.com/origranot/reduced.to/assets/62668827/09056654-9666-48a7-93cf-e70c15aa8d1d)

Mobile version:
![Capture d’écran du 2024-01-30 16-32-08](https://github.com/origranot/reduced.to/assets/62668827/5beeca51-4870-4a7a-96ee-95d56f808ce8)

**Comment by origranot** [comment]
@essofyany Nice catch!

Do you want to be assigned for this issue?
I really appreciate all your efforts you’ve done for this project!

**Comment by essofyany** [comment]
Hi @origranot 

Absolutely

My pleasure to contribute to this beautiful project.
