### ISSUE TITLE
URL link overlaps

### ISSUE THREAD

**Issue by ymoukhli** [origranot/reduced.to#693]
### Description

when creating a very long URL it overlaps

### Screenshots

![Untitled(1)](https://github.com/origranot/reduced.to/assets/77059858/1d16849b-77ba-4c1b-abd2-c694465e827e)

**Comment by origranot** [comment]
> Hello @origranot can you assign the issue to me.
> 
> Regards,

That's a good catch, I assigned you to this issue 👑
