### ISSUE TITLE
display link information in mobile view

### ISSUE THREAD

**Issue by ymoukhli** [origranot/reduced.to#701]
### Description

**current behavior :**
>when in the mobile view all the information on the link disapears, like the expiration and creation date:
![image](https://github.com/origranot/reduced.to/assets/77059858/1585ba97-9756-462c-a40d-18011c1834df)
![image](https://github.com/origranot/reduced.to/assets/77059858/e7d56231-da64-40c1-b938-8bf866e8ef5a)

 **expected behavior :**
 >users should be able to see details of the link by clicking on the dropdown then "info".

**Comment by origranot** [comment]
That's awesome idea!

Go for it @ymoukhli 🚀

**Comment by ymoukhli** [comment]
Hello @origranot,

I did add an "Info" button in mobile view only. Upon clicking on it, it will display all the missing information

![image](https://github.com/origranot/reduced.to/assets/77059858/dc6323fd-ad7c-4b5a-8234-40e64d46f48c)
![image](https://github.com/origranot/reduced.to/assets/77059858/5964b34f-3096-4b21-a07e-fef3126a4019)
![image](https://github.com/origranot/reduced.to/assets/77059858/9e07fbb7-56d6-49fd-a766-1f90d40a6952)

should we stick to this, or is there any room for improvement.

**Comment by origranot** [comment]
> Hello @origranot,
> 
> I did add an "Info" button in mobile view only. Upon clicking on it, it will display all the missing information
> 
> ![image](https://private-user-images.githubusercontent.com/77059858/302360502-dc6323fd-ad7c-4b5a-8234-40e64d46f48c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxNjcyNTAsIm5iZiI6MTcwNzE2Njk1MCwicGF0aCI6Ii83NzA1OTg1OC8zMDIzNjA1MDItZGM2MzIzZmQtYWQ3Yy00YjVhLTgyMzQtNDBlNjRkNDZmNDhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDIxMDIzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyYjNiNzRkMDhlMWEyMzViMzVjNjRmM2VmZWFmZTlkYzllYWJkNWI3ZGNhYWNkMzY3OGM1YTRmMTM4MzJhMmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ovx8aG4WQ26ZWQaVDj-u9cm8V2tewZB8b1DbVbqUPzQ) ![image](https://private-user-images.githubusercontent.com/77059858/302360850-5964b34f-3096-4b21-a07e-fef3126a4019.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxNjcyNTAsIm5iZiI6MTcwNzE2Njk1MCwicGF0aCI6Ii83NzA1OTg1OC8zMDIzNjA4NTAtNTk2NGIzNGYtMzA5Ni00YjIxLWEwN2UtZmVmMzEyNmE0MDE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDIxMDIzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwN2MyNzZiY2U2NDAxZDJmNmJiZjA3NmYzZGQxYTlkNmI1YWQ5NjE0MzQzNTM2NjYxYmFlZjMyM2MxNjM4NDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HQ_u_BU1EHVEZSUbBZ75PkF9CVNPuJlO185u6f922xg) ![image](https://private-user-images.githubusercontent.com/77059858/302361842-9e07fbb7-56d6-49fd-a766-1f90d40a6952.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxNjcyNTAsIm5iZiI6MTcwNzE2Njk1MCwicGF0aCI6Ii83NzA1OTg1OC8zMDIzNjE4NDItOWUwN2ZiYjctNTZkNi00OWZkLWE3NjYtMWY5MGQ0MGE2OTUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDIxMDIzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3ZjRlMjZlYzFkOGU5MjdjMWFjOTE3NWVjMTY3MmUyNzQwNzRmZjAxYWZiYmVkZTRhOThiZmRmNDM4MDIyMGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oXiUXPkynuJRRPegTgPw_wF0JP2iVdoKUoZI4iHAPRw)
> 
> should we stick to this, or is there any room for improvement.

Hey @ymoukhli,

That's looks great, although I am not sure this is the correct way to do it UX wise.
Maybe we can create a toggle button (near the 3 dots) to show/hide information about the link?
I had an idea to show a modal with the relevant information but I think it's even worse UX.
What do you think?

**Comment by ymoukhli** [comment]
sure thing, I ll prepare some examples.

**Comment by origranot** [comment]
Hey @ymoukhli, are you still working on that issue?

**Comment by monikkacha** [comment]
@origranot I am interested to work on this part, can you please assign to me ?

**Comment by origranot** [comment]
> @origranot I am interested to work on this part, can you please assign to me ? 
> 
> 

Awesome, I assigned you 😀

**Comment by monikkacha** [comment]
#809 Solved here
