### ISSUE TITLE
Add copy to clipboard and QR modal to dashboard

### ISSUE THREAD

**Issue by IdanDover** [origranot/reduced.to#722]
### Description

I would like to add the options to copy the url and show the qr modal in the links from the dashboard just like the links in the home screen

### Screenshots

![Screenshot 2024-03-04 195326](https://github.com/origranot/reduced.to/assets/111203178/e9dee056-1b8f-4552-996d-7617d990877f)

![Screenshot 2024-03-04 200017](https://github.com/origranot/reduced.to/assets/111203178/b5ba6e32-8c0d-41c7-b5ca-83b5f6a0aac5)

**Comment by origranot** [comment]
Hey @IdanDover,
There is already an option to copy the url from the main page.
But I think you can add another option in the dashboard (second image)
I assigned you to it!

**Comment by IdanDover** [comment]
Should I also add the QRcode modal as one of the options? I looked into the code and it seems to be specifacly for the temporary links part n the home page

**Comment by IdanDover** [comment]
I did it and it looks like this:
![image](https://github.com/origranot/reduced.to/assets/111203178/22c05203-fbb5-4f54-a942-1a3d603b4221)

when you copy it shows a toast message:
![image](https://github.com/origranot/reduced.to/assets/111203178/9d0a0ffb-e034-4a99-a958-104368cae586)

and the qr shows the QrDialog as such:
![image](https://github.com/origranot/reduced.to/assets/111203178/a629222b-5f4a-4343-bfe5-b4820f8134a1)


is this fine by you?

**Comment by origranot** [comment]
@IdanDover This looks great!

I would change the message to something like:
The url has been copied to the clipboard!

Do you mind open a PR for it?

**Comment by origranot** [comment]
Done in https://github.com/origranot/reduced.to/pull/726
