### ISSUE TITLE
Resolving Cache Persistence Issue for Deleted URLs

### ISSUE THREAD

**Issue by origranot** [origranot/reduced.to#741]
### Description

When a URL is deleted from our system, the corresponding cache entry remains active, resulting in the link being accessible until the cache expires, which can take up to 30 minutes. This behavior is not desirable as it allows deleted URLs to be accessed for a duration beyond their intended lifetime.

Expected Behavior:
Upon deletion of a URL, the associated cache entry should be invalidated immediately to ensure that the link is no longer accessible.

Steps to Reproduce:

1. Create a new URL entry.
2. Verify that the URL is accessible and cached.
3. Delete the URL entry from the dashboard
4. Verify the url is no longer in the database (postgres), but still in Redis.
5. Attempt to access the URL again.

**Comment by itsoriki** [comment]
Hi Ori! 
I would like to help solve this issue. In fact, I'm assigning you as a reviewer to my PR if you will :)

**Comment by origranot** [comment]
> Hi Ori! I would like to help solve this issue. In fact, I'm assigning you as a reviewer to my PR if you will :)

Awesome,
I will take a look 💯

**Comment by origranot** [comment]
Done in #768 768
