### ISSUE TITLE
Develop button to switch between dark and light mode

### ISSUE THREAD

**Issue by lucalves** [origranot/reduced.to#83]
Hello all!

I saw on the README.md, the suggestion to include the dark mode switch button.

I would like to work on this. I thought about leaving the light mode this way, what do you think?

![light-mode](https://user-images.githubusercontent.com/17712401/194575791-5721fee9-9ea2-42f4-b0ba-00c40a96439e.png)

If it's ok, you can assign this issue to me. I will include this.

**Comment by origranot** [comment]
It looks great.

Make sure to pull from master because your screenshot is out of date.
I want us to use a cooler button. for example: https://codepen.io/grapdroad/pen/gOzaXQg

Open a PR and work on it, it will be great!

**Comment by singharyan1007** [comment]
hi if the issue is still open can I work on it?

**Comment by lucalves** [comment]
> hi if the issue is still open can I work on it? The present ui makes it a bit tricky to implement dark and light mode.

Go ahead, @singharyan1007. I don't know this pug framework, so you can go ahead and work it out.

@origranot You can reassign the issue to him?

**Comment by origranot** [comment]
@singharyan1007 @lucalves done :)

**Comment by singharyan1007** [comment]
Hi I have added the feature of the dark and light mode and made a PR. Please review it.
